/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
#import "MSOneNoteApiModels.h"

/**
* The implementation file for type CopyStatusModel.
*/

@implementation MSOneNoteApiCopyStatusModel	

@synthesize odataType = _odataType;
@synthesize status = _status;
@synthesize createdDateTime = _createdDateTime;

- (instancetype)init {

	if (self = [super init]) {

		_odataType = @"#Microsoft.OneNote.Api.CopyStatusModel";
	}

	return self;
}

- (void)setStatus:(NSString *) status {
    _status = status;
	[self valueChanged:status forProperty:@"status"];
}
    
- (void)setCreatedDateTime:(NSDate *) createdDateTime {
    _createdDateTime = createdDateTime;
	[self valueChanged:createdDateTime forProperty:@"createdDateTime"];
}
    
@end