/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/

#import "MSOneNoteApiModels.h"

/**
* The implementation file for type MSOneNoteApiNotes.
*/

@implementation MSOneNoteApiNotes	

@synthesize odataType = _odataType;
@synthesize id = _id;
@synthesize notebooks = _notebooks;
@synthesize sections = _sections;
@synthesize sectionGroups = _sectionGroups;
@synthesize pages = _pages;
@synthesize resources = _resources;

- (instancetype)init {

	if (self = [super init]) {

		_odataType = @"#Microsoft.OneNote.Api.Notes";
		_notebooks = [[NSMutableArray alloc] initWithCollectionType:@"MSOneNoteApiNotebook"];
		_sections = [[NSMutableArray alloc] initWithCollectionType:@"MSOneNoteApiSection"];
		_sectionGroups = [[NSMutableArray alloc] initWithCollectionType:@"MSOneNoteApiSectionGroup"];
		_pages = [[NSMutableArray alloc] initWithCollectionType:@"MSOneNoteApiPage"];
		_resources = [[NSMutableArray alloc] initWithCollectionType:@"MSOneNoteApiResource"];
    }

	return self;
}

- (void)setId:(NSString *) id {
    _id = id;
	[self valueChanged:id forProperty:@"id"];
}
    
- (void)setNotebooks:(NSMutableArray *) notebooks {
    _notebooks = notebooks;
	[self valueChanged:notebooks forProperty:@"notebooks"];
}
    
- (void)setSections:(NSMutableArray *) sections {
    _sections = sections;
	[self valueChanged:sections forProperty:@"sections"];
}
    
- (void)setSectionGroups:(NSMutableArray *) sectionGroups {
    _sectionGroups = sectionGroups;
	[self valueChanged:sectionGroups forProperty:@"sectionGroups"];
}
    
- (void)setPages:(NSMutableArray *) pages {
    _pages = pages;
	[self valueChanged:pages forProperty:@"pages"];
}
    
- (void)setResources:(NSMutableArray *) resources {
    _resources = resources;
	[self valueChanged:resources forProperty:@"resources"];
}
    
@end