/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/

#import "MSEntityContainerModels.h"

/**
* The implementation file for type MSEntityContainerMessage.
*/

@implementation MSEntityContainerMessage	

@synthesize odataType = _odataType;
@synthesize Subject = _subject;
@synthesize Body = _body;
@synthesize BodyPreview = _bodyPreview;
@synthesize Importance = _importance;
@synthesize HasAttachments = _hasAttachments;
@synthesize ParentFolderId = _parentFolderId;
@synthesize From = _from;
@synthesize Sender = _sender;
@synthesize ToRecipients = _toRecipients;
@synthesize CcRecipients = _ccRecipients;
@synthesize BccRecipients = _bccRecipients;
@synthesize ReplyTo = _replyTo;
@synthesize ConversationId = _conversationId;
@synthesize UniqueBody = _uniqueBody;
@synthesize DateTimeReceived = _dateTimeReceived;
@synthesize DateTimeSent = _dateTimeSent;
@synthesize IsDeliveryReceiptRequested = _isDeliveryReceiptRequested;
@synthesize IsReadReceiptRequested = _isReadReceiptRequested;
@synthesize IsDraft = _isDraft;
@synthesize IsRead = _isRead;
@synthesize WebLink = _webLink;
@synthesize Attachments = _attachments;

- (instancetype)init {

	if (self = [super init]) {

		_odataType = @"#Microsoft.OutlookServices.Message";
		_toRecipients = [[NSMutableArray alloc] initWithCollectionType:@"MSEntityContainerRecipient"];
		_ccRecipients = [[NSMutableArray alloc] initWithCollectionType:@"MSEntityContainerRecipient"];
		_bccRecipients = [[NSMutableArray alloc] initWithCollectionType:@"MSEntityContainerRecipient"];
		_replyTo = [[NSMutableArray alloc] initWithCollectionType:@"MSEntityContainerRecipient"];
		_attachments = [[NSMutableArray alloc] initWithCollectionType:@"MSEntityContainerAttachment"];
    }

	return self;
}

- (void)setSubject:(NSString *) subject {
    _subject = subject;
	[self valueChanged:subject forProperty:@"Subject"];
}
    
- (void)setBody:(MSEntityContainerItemBody *) body {
    _body = body;
	[self valueChanged:body forProperty:@"Body"];
}
    
- (void)setBodyPreview:(NSString *) bodyPreview {
    _bodyPreview = bodyPreview;
	[self valueChanged:bodyPreview forProperty:@"BodyPreview"];
}
    - (void)setImportanceString:(NSString *)value {

	if ([value isEqualToString:@"Low"]) {	

		_importance  = MSEntityContainer_Importance_Low;
        [self valueChangedForInt:MSEntityContainer_Importance_Low forProperty:@"Importance"];
	}

	if ([value isEqualToString:@"Normal"]) {	

		_importance  = MSEntityContainer_Importance_Normal;
        [self valueChangedForInt:MSEntityContainer_Importance_Normal forProperty:@"Importance"];
	}

	if ([value isEqualToString:@"High"]) {	

		_importance  = MSEntityContainer_Importance_High;
        [self valueChangedForInt:MSEntityContainer_Importance_High forProperty:@"Importance"];
	}
}

- (void)setHasAttachments:(BOOL ) hasAttachments {
    _hasAttachments = hasAttachments;
    [self valueChangedForBool:hasAttachments forProperty:@"HasAttachments"];
}
    
- (void)setParentFolderId:(NSString *) parentFolderId {
    _parentFolderId = parentFolderId;
	[self valueChanged:parentFolderId forProperty:@"ParentFolderId"];
}
    
- (void)setFrom:(MSEntityContainerRecipient *) from {
    _from = from;
	[self valueChanged:from forProperty:@"From"];
}
    
- (void)setSender:(MSEntityContainerRecipient *) sender {
    _sender = sender;
	[self valueChanged:sender forProperty:@"Sender"];
}
    
- (void)setToRecipients:(NSMutableArray *) toRecipients {
    _toRecipients = toRecipients;
	[self valueChanged:toRecipients forProperty:@"ToRecipients"];
}
    
- (void)setCcRecipients:(NSMutableArray *) ccRecipients {
    _ccRecipients = ccRecipients;
	[self valueChanged:ccRecipients forProperty:@"CcRecipients"];
}
    
- (void)setBccRecipients:(NSMutableArray *) bccRecipients {
    _bccRecipients = bccRecipients;
	[self valueChanged:bccRecipients forProperty:@"BccRecipients"];
}
    
- (void)setReplyTo:(NSMutableArray *) replyTo {
    _replyTo = replyTo;
	[self valueChanged:replyTo forProperty:@"ReplyTo"];
}
    
- (void)setConversationId:(NSString *) conversationId {
    _conversationId = conversationId;
	[self valueChanged:conversationId forProperty:@"ConversationId"];
}
    
- (void)setUniqueBody:(MSEntityContainerItemBody *) uniqueBody {
    _uniqueBody = uniqueBody;
	[self valueChanged:uniqueBody forProperty:@"UniqueBody"];
}
    
- (void)setDateTimeReceived:(NSDate *) dateTimeReceived {
    _dateTimeReceived = dateTimeReceived;
	[self valueChanged:dateTimeReceived forProperty:@"DateTimeReceived"];
}
    
- (void)setDateTimeSent:(NSDate *) dateTimeSent {
    _dateTimeSent = dateTimeSent;
	[self valueChanged:dateTimeSent forProperty:@"DateTimeSent"];
}
    
- (void)setIsDeliveryReceiptRequested:(BOOL ) isDeliveryReceiptRequested {
    _isDeliveryReceiptRequested = isDeliveryReceiptRequested;
    [self valueChangedForBool:isDeliveryReceiptRequested forProperty:@"IsDeliveryReceiptRequested"];
}
    
- (void)setIsReadReceiptRequested:(BOOL ) isReadReceiptRequested {
    _isReadReceiptRequested = isReadReceiptRequested;
    [self valueChangedForBool:isReadReceiptRequested forProperty:@"IsReadReceiptRequested"];
}
    
- (void)setIsDraft:(BOOL ) isDraft {
    _isDraft = isDraft;
    [self valueChangedForBool:isDraft forProperty:@"IsDraft"];
}
    
- (void)setIsRead:(BOOL ) isRead {
    _isRead = isRead;
    [self valueChangedForBool:isRead forProperty:@"IsRead"];
}
    
- (void)setWebLink:(NSString *) webLink {
    _webLink = webLink;
	[self valueChanged:webLink forProperty:@"WebLink"];
}
    
- (void)setAttachments:(NSMutableArray *) attachments {
    _attachments = attachments;
	[self valueChanged:attachments forProperty:@"Attachments"];
}
    
@end