/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
#import "MSEntityContainerModels.h"

/**
* The implementation file for type Attendee.
*/

@implementation MSEntityContainerAttendee	

@synthesize odataType = _odataType;
@synthesize Status = _status;
@synthesize Type = _type;

- (instancetype)init {

	if (self = [super init]) {

		_odataType = @"#Microsoft.OutlookServices.Attendee";
	}

	return self;
}

- (void)setStatus:(MSEntityContainerResponseStatus *) status {
    _status = status;
	[self valueChanged:status forProperty:@"Status"];
}
    - (void)setTypeString:(NSString *)value {

	if ([value isEqualToString:@"Required"]) {

		_type = MSEntityContainer_AttendeeType_Required;
        [self valueChangedForInt:MSEntityContainer_AttendeeType_Required forProperty:@"Type"];
	}

	if ([value isEqualToString:@"Optional"]) {

		_type = MSEntityContainer_AttendeeType_Optional;
        [self valueChangedForInt:MSEntityContainer_AttendeeType_Optional forProperty:@"Type"];
	}

	if ([value isEqualToString:@"Resource"]) {

		_type = MSEntityContainer_AttendeeType_Resource;
        [self valueChangedForInt:MSEntityContainer_AttendeeType_Resource forProperty:@"Type"];
	}
}

@end