/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSGraphServiceApplicationFetcher;
@class MSGraphServiceExtensionPropertyFetcher;
@class MSGraphServiceUserFetcher;
@class MSGraphServiceAppRoleAssignmentFetcher;
@class MSGraphServiceGroupFetcher;
@class MSGraphServiceContactFetcher;
@class MSGraphServiceDeviceFetcher;
@class MSGraphServiceDeviceConfigurationFetcher;
@class MSGraphServiceDirectoryLinkChangeFetcher;
@class MSGraphServiceDirectoryRoleFetcher;
@class MSGraphServiceDirectoryRoleTemplateFetcher;
@class MSGraphServiceServicePrincipalFetcher;
@class MSGraphServiceTenantDetailFetcher;
@class MSGraphServiceDirectoryObjectOperations;

#import <core/core.h>
#import "MSGraphServiceModels.h"

/**
* The header for type MSGraphServiceDirectoryObjectFetcher.
*/


@interface MSGraphServiceDirectoryObjectFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSGraphServiceDirectoryObjectOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSGraphServiceDirectoryObject *directoryObject, MSOrcError *error))callback;
- (void)update:(MSGraphServiceDirectoryObject *)directoryObject callback:(void(^)(MSGraphServiceDirectoryObject *directoryObject, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSGraphServiceDirectoryObjectFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSGraphServiceDirectoryObjectFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSGraphServiceDirectoryObjectFetcher *)select:(NSString *)params;
- (MSGraphServiceDirectoryObjectFetcher *)expand:(NSString *)value;
- (MSGraphServiceApplicationFetcher *)asApplication;	
- (MSGraphServiceExtensionPropertyFetcher *)asExtensionProperty;	
- (MSGraphServiceUserFetcher *)asUser;	
- (MSGraphServiceAppRoleAssignmentFetcher *)asAppRoleAssignment;	
- (MSGraphServiceGroupFetcher *)asGroup;	
- (MSGraphServiceContactFetcher *)asContact;	
- (MSGraphServiceDeviceFetcher *)asDevice;	
- (MSGraphServiceDeviceConfigurationFetcher *)asDeviceConfiguration;	
- (MSGraphServiceDirectoryLinkChangeFetcher *)asDirectoryLinkChange;	
- (MSGraphServiceDirectoryRoleFetcher *)asDirectoryRole;	
- (MSGraphServiceDirectoryRoleTemplateFetcher *)asDirectoryRoleTemplate;	
- (MSGraphServiceServicePrincipalFetcher *)asServicePrincipal;	
- (MSGraphServiceTenantDetailFetcher *)asTenantDetail;	

@end