/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSGraphServiceCalendarFetcher;
@class MSGraphServiceCalendarCollectionFetcher;
@class MSGraphServiceCalendarGroupOperations;

#import <core/core.h>
#import "MSGraphServiceModels.h"

/**
* The header for type MSGraphServiceCalendarGroupFetcher.
*/


@interface MSGraphServiceCalendarGroupFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSGraphServiceCalendarGroupOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSGraphServiceCalendarGroup *calendarGroup, MSOrcError *error))callback;
- (void)update:(MSGraphServiceCalendarGroup *)calendarGroup callback:(void(^)(MSGraphServiceCalendarGroup *calendarGroup, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSGraphServiceCalendarGroupFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSGraphServiceCalendarGroupFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSGraphServiceCalendarGroupFetcher *)select:(NSString *)params;
- (MSGraphServiceCalendarGroupFetcher *)expand:(NSString *)value;
@property (retain, nonatomic, readonly, getter=calendars) MSGraphServiceCalendarCollectionFetcher *calendars;

- (MSGraphServiceCalendarFetcher *)getCalendarsById:(NSString*)id;


@end