/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
#import "MSGraphServiceFetchers.h"

@implementation MSGraphServiceServicePrincipalFetcher

@synthesize operations = _operations;

- (instancetype)initWithUrl:(NSString *)urlComponent parent:(id<MSOrcExecutable>)parent {

    if (self = [super initWithUrl:urlComponent parent:parent asClass:[MSGraphServiceServicePrincipal class]]) {

		_operations = [[MSGraphServiceServicePrincipalOperations alloc] initOperationWithUrl:urlComponent parent:parent];
    }

    return self;
}

- (void)update:(id)entity callback:(void (^)(MSGraphServiceServicePrincipal *servicePrincipal, MSOrcError *e))callback {

	return [super update:entity callback:callback];
}

- (void)delete:(void (^)(int status, MSOrcError *e))callback {

	return [super deleteWithCallback:callback];
}

- (MSGraphServiceServicePrincipalFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value {
    [super addCustomParametersWithName:name value:value];
    
    return self;
}

- (MSGraphServiceServicePrincipalFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value {
    [super addCustomHeaderWithName:name value:value];
    
    return self;
}

- (MSGraphServiceServicePrincipalFetcher *)select:(NSString *)params {
    [super select:params];
    
    return self;
}

- (MSGraphServiceServicePrincipalFetcher *)expand:(NSString *)value {
    [super select:value];
    
    return self;
}

- (void) readWithCallback:(void (^)(MSGraphServiceServicePrincipal *servicePrincipal, MSOrcError *error))callback {
    [super readWithCallback:^(id response, MSOrcError *error) {
        callback(response, error);
    }];
}

- (MSGraphServiceAppRoleAssignmentFetcher *)appRoleAssignedTo {

	 return [[MSGraphServiceAppRoleAssignmentFetcher alloc] initWithUrl:@"appRoleAssignedTo" parent:self asClass:[MSGraphServiceAppRoleAssignment class]];
}

- (MSGraphServiceAppRoleAssignmentCollectionFetcher *)appRoleAssignments {

    return [[MSGraphServiceAppRoleAssignmentCollectionFetcher alloc] initWithUrl:@"appRoleAssignments" parent:self asClass:[MSGraphServiceAppRoleAssignment class]];
}

- (MSGraphServiceAppRoleAssignmentFetcher *)getAppRoleAssignmentsById:(NSString *)id {

    return [[[MSGraphServiceAppRoleAssignmentCollectionFetcher alloc] initWithUrl:@"appRoleAssignments" parent:self asClass:[MSGraphServiceAppRoleAssignment class]] getById:id];
}

- (MSGraphServiceOAuth2PermissionGrantCollectionFetcher *)oauth2PermissionGrants {

    return [[MSGraphServiceOAuth2PermissionGrantCollectionFetcher alloc] initWithUrl:@"oauth2PermissionGrants" parent:self asClass:[MSGraphServiceOAuth2PermissionGrant class]];
}

- (MSGraphServiceOAuth2PermissionGrantFetcher *)getOauth2PermissionGrantsById:(NSString *)id {

    return [[[MSGraphServiceOAuth2PermissionGrantCollectionFetcher alloc] initWithUrl:@"oauth2PermissionGrants" parent:self asClass:[MSGraphServiceOAuth2PermissionGrant class]] getById:id];
}

- (MSGraphServiceDirectoryObjectCollectionFetcher *)memberOf {

    return [[MSGraphServiceDirectoryObjectCollectionFetcher alloc] initWithUrl:@"memberOf" parent:self asClass:[MSGraphServiceDirectoryObject class]];
}

- (MSGraphServiceDirectoryObjectFetcher *)getMemberOfById:(NSString *)id {

    return [[[MSGraphServiceDirectoryObjectCollectionFetcher alloc] initWithUrl:@"memberOf" parent:self asClass:[MSGraphServiceDirectoryObject class]] getById:id];
}

- (MSGraphServiceDirectoryObjectFetcher *)createdOnBehalfOf {

	 return [[MSGraphServiceDirectoryObjectFetcher alloc] initWithUrl:@"createdOnBehalfOf" parent:self asClass:[MSGraphServiceDirectoryObject class]];
}

- (MSGraphServiceDirectoryObjectCollectionFetcher *)createdObjects {

    return [[MSGraphServiceDirectoryObjectCollectionFetcher alloc] initWithUrl:@"createdObjects" parent:self asClass:[MSGraphServiceDirectoryObject class]];
}

- (MSGraphServiceDirectoryObjectFetcher *)getCreatedObjectsById:(NSString *)id {

    return [[[MSGraphServiceDirectoryObjectCollectionFetcher alloc] initWithUrl:@"createdObjects" parent:self asClass:[MSGraphServiceDirectoryObject class]] getById:id];
}

- (MSGraphServiceDirectoryObjectCollectionFetcher *)owners {

    return [[MSGraphServiceDirectoryObjectCollectionFetcher alloc] initWithUrl:@"owners" parent:self asClass:[MSGraphServiceDirectoryObject class]];
}

- (MSGraphServiceDirectoryObjectFetcher *)getOwnersById:(NSString *)id {

    return [[[MSGraphServiceDirectoryObjectCollectionFetcher alloc] initWithUrl:@"owners" parent:self asClass:[MSGraphServiceDirectoryObject class]] getById:id];
}

- (MSGraphServiceDirectoryObjectCollectionFetcher *)ownedObjects {

    return [[MSGraphServiceDirectoryObjectCollectionFetcher alloc] initWithUrl:@"ownedObjects" parent:self asClass:[MSGraphServiceDirectoryObject class]];
}

- (MSGraphServiceDirectoryObjectFetcher *)getOwnedObjectsById:(NSString *)id {

    return [[[MSGraphServiceDirectoryObjectCollectionFetcher alloc] initWithUrl:@"ownedObjects" parent:self asClass:[MSGraphServiceDirectoryObject class]] getById:id];
}

@end