/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSGraphServiceAppRoleAssignmentFetcher;
@class MSGraphServiceAppRoleAssignmentCollectionFetcher;
@class MSGraphServiceOAuth2PermissionGrantFetcher;
@class MSGraphServiceOAuth2PermissionGrantCollectionFetcher;
@class MSGraphServiceDirectoryObjectFetcher;
@class MSGraphServiceDirectoryObjectCollectionFetcher;
@class MSGraphServiceServicePrincipalOperations;

#import <core/core.h>
#import "MSGraphServiceModels.h"

/**
* The header for type MSGraphServiceServicePrincipalFetcher.
*/


@interface MSGraphServiceServicePrincipalFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSGraphServiceServicePrincipalOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSGraphServiceServicePrincipal *servicePrincipal, MSOrcError *error))callback;
- (void)update:(MSGraphServiceServicePrincipal *)servicePrincipal callback:(void(^)(MSGraphServiceServicePrincipal *servicePrincipal, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSGraphServiceServicePrincipalFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSGraphServiceServicePrincipalFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSGraphServiceServicePrincipalFetcher *)select:(NSString *)params;
- (MSGraphServiceServicePrincipalFetcher *)expand:(NSString *)value;

@property (retain, nonatomic, readonly, getter=appRoleAssignedTo) MSGraphServiceAppRoleAssignmentFetcher *appRoleAssignedTo;
@property (retain, nonatomic, readonly, getter=appRoleAssignments) MSGraphServiceAppRoleAssignmentCollectionFetcher *appRoleAssignments;

- (MSGraphServiceAppRoleAssignmentFetcher *)getAppRoleAssignmentsById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=oauth2PermissionGrants) MSGraphServiceOAuth2PermissionGrantCollectionFetcher *oauth2PermissionGrants;

- (MSGraphServiceOAuth2PermissionGrantFetcher *)getOauth2PermissionGrantsById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=memberOf) MSGraphServiceDirectoryObjectCollectionFetcher *memberOf;

- (MSGraphServiceDirectoryObjectFetcher *)getMemberOfById:(NSString*)id;


@property (retain, nonatomic, readonly, getter=createdOnBehalfOf) MSGraphServiceDirectoryObjectFetcher *createdOnBehalfOf;
@property (retain, nonatomic, readonly, getter=createdObjects) MSGraphServiceDirectoryObjectCollectionFetcher *createdObjects;

- (MSGraphServiceDirectoryObjectFetcher *)getCreatedObjectsById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=owners) MSGraphServiceDirectoryObjectCollectionFetcher *owners;

- (MSGraphServiceDirectoryObjectFetcher *)getOwnersById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=ownedObjects) MSGraphServiceDirectoryObjectCollectionFetcher *ownedObjects;

- (MSGraphServiceDirectoryObjectFetcher *)getOwnedObjectsById:(NSString*)id;


@end