/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSGraphServiceDirectoryObjectFetcher;
@class MSGraphServiceDirectoryObjectCollectionFetcher;
@class MSGraphServiceDeviceOperations;

#import <core/core.h>
#import "MSGraphServiceModels.h"

/**
* The header for type MSGraphServiceDeviceFetcher.
*/


@interface MSGraphServiceDeviceFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSGraphServiceDeviceOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSGraphServiceDevice *device, MSOrcError *error))callback;
- (void)update:(MSGraphServiceDevice *)device callback:(void(^)(MSGraphServiceDevice *device, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSGraphServiceDeviceFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSGraphServiceDeviceFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSGraphServiceDeviceFetcher *)select:(NSString *)params;
- (MSGraphServiceDeviceFetcher *)expand:(NSString *)value;
@property (retain, nonatomic, readonly, getter=registeredOwners) MSGraphServiceDirectoryObjectCollectionFetcher *registeredOwners;

- (MSGraphServiceDirectoryObjectFetcher *)getRegisteredOwnersById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=registeredUsers) MSGraphServiceDirectoryObjectCollectionFetcher *registeredUsers;

- (MSGraphServiceDirectoryObjectFetcher *)getRegisteredUsersById:(NSString*)id;


@end