/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSGraphServiceUserFetcher;
@class MSGraphServiceItemFetcher;
@class MSGraphServiceItemCollectionFetcher;
@class MSGraphServiceFileFetcher;
@class MSGraphServiceFolderFetcher;
@class MSGraphServiceItemOperations;

#import <core/core.h>
#import "MSGraphServiceModels.h"

/**
* The header for type MSGraphServiceItemFetcher.
*/


@interface MSGraphServiceItemFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSGraphServiceItemOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSGraphServiceItem *item, MSOrcError *error))callback;
- (void)update:(MSGraphServiceItem *)item callback:(void(^)(MSGraphServiceItem *item, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSGraphServiceItemFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSGraphServiceItemFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSGraphServiceItemFetcher *)select:(NSString *)params;
- (MSGraphServiceItemFetcher *)expand:(NSString *)value;

@property (retain, nonatomic, readonly, getter=createdByUser) MSGraphServiceUserFetcher *createdByUser;

@property (retain, nonatomic, readonly, getter=lastModifiedByUser) MSGraphServiceUserFetcher *lastModifiedByUser;
@property (retain, nonatomic, readonly, getter=children) MSGraphServiceItemCollectionFetcher *children;

- (MSGraphServiceItemFetcher *)getChildrenById:(NSString*)id;

- (MSGraphServiceFileFetcher *)asFile;	
- (MSGraphServiceFolderFetcher *)asFolder;	

@end