/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
#import "MSGraphServiceFetchers.h"

/**
* The implementation file for type MSGraphServiceClient.
*/

@implementation MSGraphServiceClient

- (instancetype)initWithUrl:(NSString *)url dependencyResolver:(id<MSOrcDependencyResolver>)resolver {

    return [super initWithUrl:url dependencyResolver:resolver];
}

- (MSGraphServiceDirectoryObjectCollectionFetcher *)directoryObjects {

	return [[MSGraphServiceDirectoryObjectCollectionFetcher alloc] initWithUrl:@"directoryObjects" parent:self];
}
- (MSGraphServiceApplicationCollectionFetcher *)applications {

	return [[MSGraphServiceApplicationCollectionFetcher alloc] initWithUrl:@"applications" parent:self];
}
- (MSGraphServiceContactCollectionFetcher *)contacts {

	return [[MSGraphServiceContactCollectionFetcher alloc] initWithUrl:@"contacts" parent:self];
}
- (MSGraphServiceDeviceConfigurationCollectionFetcher *)deviceConfiguration {

	return [[MSGraphServiceDeviceConfigurationCollectionFetcher alloc] initWithUrl:@"deviceConfiguration" parent:self];
}
- (MSGraphServiceDeviceCollectionFetcher *)devices {

	return [[MSGraphServiceDeviceCollectionFetcher alloc] initWithUrl:@"devices" parent:self];
}
- (MSGraphServiceGroupCollectionFetcher *)groups {

	return [[MSGraphServiceGroupCollectionFetcher alloc] initWithUrl:@"groups" parent:self];
}
- (MSGraphServiceDirectoryRoleCollectionFetcher *)directoryRoles {

	return [[MSGraphServiceDirectoryRoleCollectionFetcher alloc] initWithUrl:@"directoryRoles" parent:self];
}
- (MSGraphServiceDirectoryRoleTemplateCollectionFetcher *)directoryRoleTemplates {

	return [[MSGraphServiceDirectoryRoleTemplateCollectionFetcher alloc] initWithUrl:@"directoryRoleTemplates" parent:self];
}
- (MSGraphServiceServicePrincipalCollectionFetcher *)servicePrincipals {

	return [[MSGraphServiceServicePrincipalCollectionFetcher alloc] initWithUrl:@"servicePrincipals" parent:self];
}
- (MSGraphServiceTenantDetailCollectionFetcher *)tenantDetails {

	return [[MSGraphServiceTenantDetailCollectionFetcher alloc] initWithUrl:@"tenantDetails" parent:self];
}
- (MSGraphServiceUserCollectionFetcher *)users {

	return [[MSGraphServiceUserCollectionFetcher alloc] initWithUrl:@"users" parent:self];
}
- (MSGraphServiceOAuth2PermissionGrantCollectionFetcher *)oauth2PermissionGrants {

	return [[MSGraphServiceOAuth2PermissionGrantCollectionFetcher alloc] initWithUrl:@"oauth2PermissionGrants" parent:self];
}
- (MSGraphServiceSubscribedSkuCollectionFetcher *)subscribedSkus {

	return [[MSGraphServiceSubscribedSkuCollectionFetcher alloc] initWithUrl:@"subscribedSkus" parent:self];
}

@end