/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSGraphServiceMessageFetcher;
@class MSGraphServiceEventFetcher;
@class MSGraphServicePostFetcher;
@class MSGraphServiceOutlookItemOperations;

#import <core/core.h>
#import "MSGraphServiceModels.h"

/**
* The header for type MSGraphServiceOutlookItemFetcher.
*/


@interface MSGraphServiceOutlookItemFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSGraphServiceOutlookItemOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSGraphServiceOutlookItem *outlookItem, MSOrcError *error))callback;
- (void)update:(MSGraphServiceOutlookItem *)outlookItem callback:(void(^)(MSGraphServiceOutlookItem *outlookItem, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSGraphServiceOutlookItemFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSGraphServiceOutlookItemFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSGraphServiceOutlookItemFetcher *)select:(NSString *)params;
- (MSGraphServiceOutlookItemFetcher *)expand:(NSString *)value;
- (MSGraphServiceMessageFetcher *)asMessage;	
- (MSGraphServiceEventFetcher *)asEvent;	
- (MSGraphServicePostFetcher *)asPost;	

@end