/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSGraphServiceDirectoryObjectFetcher;
@class MSGraphServiceDirectoryObjectCollectionFetcher;
@class MSGraphServiceDirectoryRoleOperations;

#import <core/core.h>
#import "MSGraphServiceModels.h"

/**
* The header for type MSGraphServiceDirectoryRoleFetcher.
*/


@interface MSGraphServiceDirectoryRoleFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSGraphServiceDirectoryRoleOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSGraphServiceDirectoryRole *directoryRole, MSOrcError *error))callback;
- (void)update:(MSGraphServiceDirectoryRole *)directoryRole callback:(void(^)(MSGraphServiceDirectoryRole *directoryRole, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSGraphServiceDirectoryRoleFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSGraphServiceDirectoryRoleFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSGraphServiceDirectoryRoleFetcher *)select:(NSString *)params;
- (MSGraphServiceDirectoryRoleFetcher *)expand:(NSString *)value;
@property (retain, nonatomic, readonly, getter=members) MSGraphServiceDirectoryObjectCollectionFetcher *members;

- (MSGraphServiceDirectoryObjectFetcher *)getMembersById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=memberOf) MSGraphServiceDirectoryObjectCollectionFetcher *memberOf;

- (MSGraphServiceDirectoryObjectFetcher *)getMemberOfById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=owners) MSGraphServiceDirectoryObjectCollectionFetcher *owners;

- (MSGraphServiceDirectoryObjectFetcher *)getOwnersById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=ownedObjects) MSGraphServiceDirectoryObjectCollectionFetcher *ownedObjects;

- (MSGraphServiceDirectoryObjectFetcher *)getOwnedObjectsById:(NSString*)id;


@end