/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSGraphServiceExtensionPropertyFetcher;
@class MSGraphServiceExtensionPropertyCollectionFetcher;
@class MSGraphServiceDirectoryObjectFetcher;
@class MSGraphServiceDirectoryObjectCollectionFetcher;
@class MSGraphServiceApplicationOperations;

#import <core/core.h>
#import "MSGraphServiceModels.h"

/**
* The header for type MSGraphServiceApplicationFetcher.
*/


@interface MSGraphServiceApplicationFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSGraphServiceApplicationOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSGraphServiceApplication *application, MSOrcError *error))callback;
- (void)update:(MSGraphServiceApplication *)application callback:(void(^)(MSGraphServiceApplication *application, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSGraphServiceApplicationFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSGraphServiceApplicationFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSGraphServiceApplicationFetcher *)select:(NSString *)params;
- (MSGraphServiceApplicationFetcher *)expand:(NSString *)value;
@property (retain, nonatomic, readonly, getter=extensionProperties) MSGraphServiceExtensionPropertyCollectionFetcher *extensionProperties;

- (MSGraphServiceExtensionPropertyFetcher *)getExtensionPropertiesById:(NSString*)id;


@property (retain, nonatomic, readonly, getter=createdOnBehalfOf) MSGraphServiceDirectoryObjectFetcher *createdOnBehalfOf;
@property (retain, nonatomic, readonly, getter=owners) MSGraphServiceDirectoryObjectCollectionFetcher *owners;

- (MSGraphServiceDirectoryObjectFetcher *)getOwnersById:(NSString*)id;


@end