/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSGraphServiceSubscribedSkuOperations;

#import <core/core.h>
#import "MSGraphServiceModels.h"

/**
* The header for type MSGraphServiceSubscribedSkuFetcher.
*/


@interface MSGraphServiceSubscribedSkuFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSGraphServiceSubscribedSkuOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSGraphServiceSubscribedSku *subscribedSku, MSOrcError *error))callback;
- (void)update:(MSGraphServiceSubscribedSku *)subscribedSku callback:(void(^)(MSGraphServiceSubscribedSku *subscribedSku, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSGraphServiceSubscribedSkuFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSGraphServiceSubscribedSkuFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSGraphServiceSubscribedSkuFetcher *)select:(NSString *)params;
- (MSGraphServiceSubscribedSkuFetcher *)expand:(NSString *)value;

@end