/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSGraphServiceAttachmentFetcher;
@class MSGraphServiceAttachmentCollectionFetcher;
@class MSGraphServicePostFetcher;
@class MSGraphServicePostOperations;

#import <core/core.h>
#import "MSGraphServiceModels.h"

/**
* The header for type MSGraphServicePostFetcher.
*/


@interface MSGraphServicePostFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSGraphServicePostOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSGraphServicePost *post, MSOrcError *error))callback;
- (void)update:(MSGraphServicePost *)post callback:(void(^)(MSGraphServicePost *post, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSGraphServicePostFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSGraphServicePostFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSGraphServicePostFetcher *)select:(NSString *)params;
- (MSGraphServicePostFetcher *)expand:(NSString *)value;
@property (retain, nonatomic, readonly, getter=attachments) MSGraphServiceAttachmentCollectionFetcher *attachments;

- (MSGraphServiceAttachmentFetcher *)getAttachmentsById:(NSString*)id;


@property (retain, nonatomic, readonly, getter=inReplyTo) MSGraphServicePostFetcher *inReplyTo;

@end