/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
#import "MSGraphServiceFetchers.h"

@implementation MSGraphServiceUserFetcher

@synthesize operations = _operations;

- (instancetype)initWithUrl:(NSString *)urlComponent parent:(id<MSOrcExecutable>)parent {

    if (self = [super initWithUrl:urlComponent parent:parent asClass:[MSGraphServiceUser class]]) {

		_operations = [[MSGraphServiceUserOperations alloc] initOperationWithUrl:urlComponent parent:parent];
    }

    return self;
}

- (void)update:(id)entity callback:(void (^)(MSGraphServiceUser *user, MSOrcError *e))callback {

	return [super update:entity callback:callback];
}

- (void)delete:(void (^)(int status, MSOrcError *e))callback {

	return [super deleteWithCallback:callback];
}

- (MSGraphServiceUserFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value {
    [super addCustomParametersWithName:name value:value];
    
    return self;
}

- (MSGraphServiceUserFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value {
    [super addCustomHeaderWithName:name value:value];
    
    return self;
}

- (MSGraphServiceUserFetcher *)select:(NSString *)params {
    [super select:params];
    
    return self;
}

- (MSGraphServiceUserFetcher *)expand:(NSString *)value {
    [super select:value];
    
    return self;
}

- (void) readWithCallback:(void (^)(MSGraphServiceUser *user, MSOrcError *error))callback {
    [super readWithCallback:^(id response, MSOrcError *error) {
        callback(response, error);
    }];
}

- (MSGraphServiceAppRoleAssignmentCollectionFetcher *)appRoleAssignments {

    return [[MSGraphServiceAppRoleAssignmentCollectionFetcher alloc] initWithUrl:@"appRoleAssignments" parent:self asClass:[MSGraphServiceAppRoleAssignment class]];
}

- (MSGraphServiceAppRoleAssignmentFetcher *)getAppRoleAssignmentsById:(NSString *)id {

    return [[[MSGraphServiceAppRoleAssignmentCollectionFetcher alloc] initWithUrl:@"appRoleAssignments" parent:self asClass:[MSGraphServiceAppRoleAssignment class]] getById:id];
}

- (MSGraphServiceOAuth2PermissionGrantCollectionFetcher *)oauth2PermissionGrants {

    return [[MSGraphServiceOAuth2PermissionGrantCollectionFetcher alloc] initWithUrl:@"oauth2PermissionGrants" parent:self asClass:[MSGraphServiceOAuth2PermissionGrant class]];
}

- (MSGraphServiceOAuth2PermissionGrantFetcher *)getOauth2PermissionGrantsById:(NSString *)id {

    return [[[MSGraphServiceOAuth2PermissionGrantCollectionFetcher alloc] initWithUrl:@"oauth2PermissionGrants" parent:self asClass:[MSGraphServiceOAuth2PermissionGrant class]] getById:id];
}

- (MSGraphServiceDirectoryObjectCollectionFetcher *)ownedDevices {

    return [[MSGraphServiceDirectoryObjectCollectionFetcher alloc] initWithUrl:@"ownedDevices" parent:self asClass:[MSGraphServiceDirectoryObject class]];
}

- (MSGraphServiceDirectoryObjectFetcher *)getOwnedDevicesById:(NSString *)id {

    return [[[MSGraphServiceDirectoryObjectCollectionFetcher alloc] initWithUrl:@"ownedDevices" parent:self asClass:[MSGraphServiceDirectoryObject class]] getById:id];
}

- (MSGraphServiceDirectoryObjectCollectionFetcher *)registeredDevices {

    return [[MSGraphServiceDirectoryObjectCollectionFetcher alloc] initWithUrl:@"registeredDevices" parent:self asClass:[MSGraphServiceDirectoryObject class]];
}

- (MSGraphServiceDirectoryObjectFetcher *)getRegisteredDevicesById:(NSString *)id {

    return [[[MSGraphServiceDirectoryObjectCollectionFetcher alloc] initWithUrl:@"registeredDevices" parent:self asClass:[MSGraphServiceDirectoryObject class]] getById:id];
}

- (MSGraphServiceDirectoryObjectFetcher *)manager {

	 return [[MSGraphServiceDirectoryObjectFetcher alloc] initWithUrl:@"manager" parent:self asClass:[MSGraphServiceDirectoryObject class]];
}

- (MSGraphServiceDirectoryObjectCollectionFetcher *)directReports {

    return [[MSGraphServiceDirectoryObjectCollectionFetcher alloc] initWithUrl:@"directReports" parent:self asClass:[MSGraphServiceDirectoryObject class]];
}

- (MSGraphServiceDirectoryObjectFetcher *)getDirectReportsById:(NSString *)id {

    return [[[MSGraphServiceDirectoryObjectCollectionFetcher alloc] initWithUrl:@"directReports" parent:self asClass:[MSGraphServiceDirectoryObject class]] getById:id];
}

- (MSGraphServiceDirectoryObjectCollectionFetcher *)memberOf {

    return [[MSGraphServiceDirectoryObjectCollectionFetcher alloc] initWithUrl:@"memberOf" parent:self asClass:[MSGraphServiceDirectoryObject class]];
}

- (MSGraphServiceDirectoryObjectFetcher *)getMemberOfById:(NSString *)id {

    return [[[MSGraphServiceDirectoryObjectCollectionFetcher alloc] initWithUrl:@"memberOf" parent:self asClass:[MSGraphServiceDirectoryObject class]] getById:id];
}

- (MSGraphServiceDirectoryObjectCollectionFetcher *)createdObjects {

    return [[MSGraphServiceDirectoryObjectCollectionFetcher alloc] initWithUrl:@"createdObjects" parent:self asClass:[MSGraphServiceDirectoryObject class]];
}

- (MSGraphServiceDirectoryObjectFetcher *)getCreatedObjectsById:(NSString *)id {

    return [[[MSGraphServiceDirectoryObjectCollectionFetcher alloc] initWithUrl:@"createdObjects" parent:self asClass:[MSGraphServiceDirectoryObject class]] getById:id];
}

- (MSGraphServiceDirectoryObjectCollectionFetcher *)ownedObjects {

    return [[MSGraphServiceDirectoryObjectCollectionFetcher alloc] initWithUrl:@"ownedObjects" parent:self asClass:[MSGraphServiceDirectoryObject class]];
}

- (MSGraphServiceDirectoryObjectFetcher *)getOwnedObjectsById:(NSString *)id {

    return [[[MSGraphServiceDirectoryObjectCollectionFetcher alloc] initWithUrl:@"ownedObjects" parent:self asClass:[MSGraphServiceDirectoryObject class]] getById:id];
}

- (MSGraphServiceMessageCollectionFetcher *)messages {

    return [[MSGraphServiceMessageCollectionFetcher alloc] initWithUrl:@"Messages" parent:self asClass:[MSGraphServiceMessage class]];
}

- (MSGraphServiceMessageFetcher *)getMessagesById:(NSString *)id {

    return [[[MSGraphServiceMessageCollectionFetcher alloc] initWithUrl:@"Messages" parent:self asClass:[MSGraphServiceMessage class]] getById:id];
}

- (MSGraphServiceCalendarCollectionFetcher *)calendars {

    return [[MSGraphServiceCalendarCollectionFetcher alloc] initWithUrl:@"Calendars" parent:self asClass:[MSGraphServiceCalendar class]];
}

- (MSGraphServiceCalendarFetcher *)getCalendarsById:(NSString *)id {

    return [[[MSGraphServiceCalendarCollectionFetcher alloc] initWithUrl:@"Calendars" parent:self asClass:[MSGraphServiceCalendar class]] getById:id];
}

- (MSGraphServiceCalendarFetcher *)calendar {

	 return [[MSGraphServiceCalendarFetcher alloc] initWithUrl:@"Calendar" parent:self asClass:[MSGraphServiceCalendar class]];
}

- (MSGraphServiceCalendarGroupCollectionFetcher *)calendarGroups {

    return [[MSGraphServiceCalendarGroupCollectionFetcher alloc] initWithUrl:@"CalendarGroups" parent:self asClass:[MSGraphServiceCalendarGroup class]];
}

- (MSGraphServiceCalendarGroupFetcher *)getCalendarGroupsById:(NSString *)id {

    return [[[MSGraphServiceCalendarGroupCollectionFetcher alloc] initWithUrl:@"CalendarGroups" parent:self asClass:[MSGraphServiceCalendarGroup class]] getById:id];
}

- (MSGraphServiceEventCollectionFetcher *)events {

    return [[MSGraphServiceEventCollectionFetcher alloc] initWithUrl:@"Events" parent:self asClass:[MSGraphServiceEvent class]];
}

- (MSGraphServiceEventFetcher *)getEventsById:(NSString *)id {

    return [[[MSGraphServiceEventCollectionFetcher alloc] initWithUrl:@"Events" parent:self asClass:[MSGraphServiceEvent class]] getById:id];
}

- (MSGraphServiceEventCollectionFetcher *)calendarView {

    return [[MSGraphServiceEventCollectionFetcher alloc] initWithUrl:@"CalendarView" parent:self asClass:[MSGraphServiceEvent class]];
}

- (MSGraphServiceEventFetcher *)getCalendarViewById:(NSString *)id {

    return [[[MSGraphServiceEventCollectionFetcher alloc] initWithUrl:@"CalendarView" parent:self asClass:[MSGraphServiceEvent class]] getById:id];
}

- (MSGraphServicePhotoFetcher *)userPhoto {

	 return [[MSGraphServicePhotoFetcher alloc] initWithUrl:@"UserPhoto" parent:self asClass:[MSGraphServicePhoto class]];
}

- (MSGraphServicePhotoCollectionFetcher *)userPhotos {

    return [[MSGraphServicePhotoCollectionFetcher alloc] initWithUrl:@"UserPhotos" parent:self asClass:[MSGraphServicePhoto class]];
}

- (MSGraphServicePhotoFetcher *)getUserPhotosById:(NSString *)id {

    return [[[MSGraphServicePhotoCollectionFetcher alloc] initWithUrl:@"UserPhotos" parent:self asClass:[MSGraphServicePhoto class]] getById:id];
}

- (MSGraphServiceFileCollectionFetcher *)trendingAround {

    return [[MSGraphServiceFileCollectionFetcher alloc] initWithUrl:@"TrendingAround" parent:self asClass:[MSGraphServiceFile class]];
}

- (MSGraphServiceFileFetcher *)getTrendingAroundById:(NSString *)id {

    return [[[MSGraphServiceFileCollectionFetcher alloc] initWithUrl:@"TrendingAround" parent:self asClass:[MSGraphServiceFile class]] getById:id];
}

- (MSGraphServiceUserCollectionFetcher *)workingWith {

    return [[MSGraphServiceUserCollectionFetcher alloc] initWithUrl:@"WorkingWith" parent:self asClass:[MSGraphServiceUser class]];
}

- (MSGraphServiceUserFetcher *)getWorkingWithById:(NSString *)id {

    return [[[MSGraphServiceUserCollectionFetcher alloc] initWithUrl:@"WorkingWith" parent:self asClass:[MSGraphServiceUser class]] getById:id];
}

- (MSGraphServiceGroupCollectionFetcher *)joinedGroups {

    return [[MSGraphServiceGroupCollectionFetcher alloc] initWithUrl:@"JoinedGroups" parent:self asClass:[MSGraphServiceGroup class]];
}

- (MSGraphServiceGroupFetcher *)getJoinedGroupsById:(NSString *)id {

    return [[[MSGraphServiceGroupCollectionFetcher alloc] initWithUrl:@"JoinedGroups" parent:self asClass:[MSGraphServiceGroup class]] getById:id];
}

- (MSGraphServiceDriveFetcher *)drive {

	 return [[MSGraphServiceDriveFetcher alloc] initWithUrl:@"drive" parent:self asClass:[MSGraphServiceDrive class]];
}

- (MSGraphServiceItemCollectionFetcher *)files {

    return [[MSGraphServiceItemCollectionFetcher alloc] initWithUrl:@"files" parent:self asClass:[MSGraphServiceItem class]];
}

- (MSGraphServiceItemFetcher *)getFilesById:(NSString *)id {

    return [[[MSGraphServiceItemCollectionFetcher alloc] initWithUrl:@"files" parent:self asClass:[MSGraphServiceItem class]] getById:id];
}

@end