/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
#import "MSGraphServiceFetchers.h"

@implementation MSGraphServiceItemFetcher

@synthesize operations = _operations;

- (instancetype)initWithUrl:(NSString *)urlComponent parent:(id<MSOrcExecutable>)parent {

    if (self = [super initWithUrl:urlComponent parent:parent asClass:[MSGraphServiceItem class]]) {

		_operations = [[MSGraphServiceItemOperations alloc] initOperationWithUrl:urlComponent parent:parent];
    }

    return self;
}

- (void)update:(id)entity callback:(void (^)(MSGraphServiceItem *item, MSOrcError *e))callback {

	return [super update:entity callback:callback];
}

- (void)delete:(void (^)(int status, MSOrcError *e))callback {

	return [super deleteWithCallback:callback];
}

- (MSGraphServiceItemFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value {
    [super addCustomParametersWithName:name value:value];
    
    return self;
}

- (MSGraphServiceItemFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value {
    [super addCustomHeaderWithName:name value:value];
    
    return self;
}

- (MSGraphServiceItemFetcher *)select:(NSString *)params {
    [super select:params];
    
    return self;
}

- (MSGraphServiceItemFetcher *)expand:(NSString *)value {
    [super select:value];
    
    return self;
}

- (void) readWithCallback:(void (^)(MSGraphServiceItem *item, MSOrcError *error))callback {
    [super readWithCallback:^(id response, MSOrcError *error) {
        callback(response, error);
    }];
}

- (MSGraphServiceUserFetcher *)createdByUser {

	 return [[MSGraphServiceUserFetcher alloc] initWithUrl:@"createdByUser" parent:self asClass:[MSGraphServiceUser class]];
}

- (MSGraphServiceUserFetcher *)lastModifiedByUser {

	 return [[MSGraphServiceUserFetcher alloc] initWithUrl:@"lastModifiedByUser" parent:self asClass:[MSGraphServiceUser class]];
}

- (MSGraphServiceItemCollectionFetcher *)children {

    return [[MSGraphServiceItemCollectionFetcher alloc] initWithUrl:@"children" parent:self asClass:[MSGraphServiceItem class]];
}

- (MSGraphServiceItemFetcher *)getChildrenById:(NSString *)id {

    return [[[MSGraphServiceItemCollectionFetcher alloc] initWithUrl:@"children" parent:self asClass:[MSGraphServiceItem class]] getById:id];
}

- (MSGraphServiceFileFetcher *)asFile {

	return [[MSGraphServiceFileFetcher alloc] initWithUrl:@"" parent:self asClass:[MSGraphServiceFile class]];
}

- (MSGraphServiceFolderFetcher *)asFolder {

	return [[MSGraphServiceFolderFetcher alloc] initWithUrl:@"" parent:self asClass:[MSGraphServiceFolder class]];
}

@end