/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSGraphServiceAppRoleAssignmentFetcher;
@class MSGraphServiceAppRoleAssignmentCollectionFetcher;
@class MSGraphServiceOAuth2PermissionGrantFetcher;
@class MSGraphServiceOAuth2PermissionGrantCollectionFetcher;
@class MSGraphServiceDirectoryObjectFetcher;
@class MSGraphServiceDirectoryObjectCollectionFetcher;
@class MSGraphServiceMessageFetcher;
@class MSGraphServiceMessageCollectionFetcher;
@class MSGraphServiceCalendarFetcher;
@class MSGraphServiceCalendarCollectionFetcher;
@class MSGraphServiceCalendarGroupFetcher;
@class MSGraphServiceCalendarGroupCollectionFetcher;
@class MSGraphServiceEventFetcher;
@class MSGraphServiceEventCollectionFetcher;
@class MSGraphServicePhotoFetcher;
@class MSGraphServicePhotoCollectionFetcher;
@class MSGraphServiceFileFetcher;
@class MSGraphServiceFileCollectionFetcher;
@class MSGraphServiceUserFetcher;
@class MSGraphServiceUserCollectionFetcher;
@class MSGraphServiceGroupFetcher;
@class MSGraphServiceGroupCollectionFetcher;
@class MSGraphServiceDriveFetcher;
@class MSGraphServiceItemFetcher;
@class MSGraphServiceItemCollectionFetcher;
@class MSGraphServiceUserOperations;

#import <core/core.h>
#import "MSGraphServiceModels.h"

/**
* The header for type MSGraphServiceUserFetcher.
*/


@interface MSGraphServiceUserFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSGraphServiceUserOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSGraphServiceUser *user, MSOrcError *error))callback;
- (void)update:(MSGraphServiceUser *)user callback:(void(^)(MSGraphServiceUser *user, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSGraphServiceUserFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSGraphServiceUserFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSGraphServiceUserFetcher *)select:(NSString *)params;
- (MSGraphServiceUserFetcher *)expand:(NSString *)value;
@property (retain, nonatomic, readonly, getter=appRoleAssignments) MSGraphServiceAppRoleAssignmentCollectionFetcher *appRoleAssignments;

- (MSGraphServiceAppRoleAssignmentFetcher *)getAppRoleAssignmentsById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=oauth2PermissionGrants) MSGraphServiceOAuth2PermissionGrantCollectionFetcher *oauth2PermissionGrants;

- (MSGraphServiceOAuth2PermissionGrantFetcher *)getOauth2PermissionGrantsById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=ownedDevices) MSGraphServiceDirectoryObjectCollectionFetcher *ownedDevices;

- (MSGraphServiceDirectoryObjectFetcher *)getOwnedDevicesById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=registeredDevices) MSGraphServiceDirectoryObjectCollectionFetcher *registeredDevices;

- (MSGraphServiceDirectoryObjectFetcher *)getRegisteredDevicesById:(NSString*)id;


@property (retain, nonatomic, readonly, getter=manager) MSGraphServiceDirectoryObjectFetcher *manager;
@property (retain, nonatomic, readonly, getter=directReports) MSGraphServiceDirectoryObjectCollectionFetcher *directReports;

- (MSGraphServiceDirectoryObjectFetcher *)getDirectReportsById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=memberOf) MSGraphServiceDirectoryObjectCollectionFetcher *memberOf;

- (MSGraphServiceDirectoryObjectFetcher *)getMemberOfById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=createdObjects) MSGraphServiceDirectoryObjectCollectionFetcher *createdObjects;

- (MSGraphServiceDirectoryObjectFetcher *)getCreatedObjectsById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=ownedObjects) MSGraphServiceDirectoryObjectCollectionFetcher *ownedObjects;

- (MSGraphServiceDirectoryObjectFetcher *)getOwnedObjectsById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=messages) MSGraphServiceMessageCollectionFetcher *messages;

- (MSGraphServiceMessageFetcher *)getMessagesById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=calendars) MSGraphServiceCalendarCollectionFetcher *calendars;

- (MSGraphServiceCalendarFetcher *)getCalendarsById:(NSString*)id;


@property (retain, nonatomic, readonly, getter=calendar) MSGraphServiceCalendarFetcher *calendar;
@property (retain, nonatomic, readonly, getter=calendarGroups) MSGraphServiceCalendarGroupCollectionFetcher *calendarGroups;

- (MSGraphServiceCalendarGroupFetcher *)getCalendarGroupsById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=events) MSGraphServiceEventCollectionFetcher *events;

- (MSGraphServiceEventFetcher *)getEventsById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=calendarView) MSGraphServiceEventCollectionFetcher *calendarView;

- (MSGraphServiceEventFetcher *)getCalendarViewById:(NSString*)id;


@property (retain, nonatomic, readonly, getter=userPhoto) MSGraphServicePhotoFetcher *userPhoto;
@property (retain, nonatomic, readonly, getter=userPhotos) MSGraphServicePhotoCollectionFetcher *userPhotos;

- (MSGraphServicePhotoFetcher *)getUserPhotosById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=trendingAround) MSGraphServiceFileCollectionFetcher *trendingAround;

- (MSGraphServiceFileFetcher *)getTrendingAroundById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=workingWith) MSGraphServiceUserCollectionFetcher *workingWith;

- (MSGraphServiceUserFetcher *)getWorkingWithById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=joinedGroups) MSGraphServiceGroupCollectionFetcher *joinedGroups;

- (MSGraphServiceGroupFetcher *)getJoinedGroupsById:(NSString*)id;


@property (retain, nonatomic, readonly, getter=drive) MSGraphServiceDriveFetcher *drive;
@property (retain, nonatomic, readonly, getter=files) MSGraphServiceItemCollectionFetcher *files;

- (MSGraphServiceItemFetcher *)getFilesById:(NSString*)id;


@end