/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
#import "MSGraphServiceFetchers.h"

@implementation MSGraphServiceDirectoryObjectFetcher

@synthesize operations = _operations;

- (instancetype)initWithUrl:(NSString *)urlComponent parent:(id<MSOrcExecutable>)parent {

    if (self = [super initWithUrl:urlComponent parent:parent asClass:[MSGraphServiceDirectoryObject class]]) {

		_operations = [[MSGraphServiceDirectoryObjectOperations alloc] initOperationWithUrl:urlComponent parent:parent];
    }

    return self;
}

- (void)update:(id)entity callback:(void (^)(MSGraphServiceDirectoryObject *directoryObject, MSOrcError *e))callback {

	return [super update:entity callback:callback];
}

- (void)delete:(void (^)(int status, MSOrcError *e))callback {

	return [super deleteWithCallback:callback];
}

- (MSGraphServiceDirectoryObjectFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value {
    [super addCustomParametersWithName:name value:value];
    
    return self;
}

- (MSGraphServiceDirectoryObjectFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value {
    [super addCustomHeaderWithName:name value:value];
    
    return self;
}

- (MSGraphServiceDirectoryObjectFetcher *)select:(NSString *)params {
    [super select:params];
    
    return self;
}

- (MSGraphServiceDirectoryObjectFetcher *)expand:(NSString *)value {
    [super select:value];
    
    return self;
}

- (void) readWithCallback:(void (^)(MSGraphServiceDirectoryObject *directoryObject, MSOrcError *error))callback {
    [super readWithCallback:^(id response, MSOrcError *error) {
        callback(response, error);
    }];
}

- (MSGraphServiceApplicationFetcher *)asApplication {

	return [[MSGraphServiceApplicationFetcher alloc] initWithUrl:@"" parent:self asClass:[MSGraphServiceApplication class]];
}

- (MSGraphServiceExtensionPropertyFetcher *)asExtensionProperty {

	return [[MSGraphServiceExtensionPropertyFetcher alloc] initWithUrl:@"" parent:self asClass:[MSGraphServiceExtensionProperty class]];
}

- (MSGraphServiceUserFetcher *)asUser {

	return [[MSGraphServiceUserFetcher alloc] initWithUrl:@"" parent:self asClass:[MSGraphServiceUser class]];
}

- (MSGraphServiceAppRoleAssignmentFetcher *)asAppRoleAssignment {

	return [[MSGraphServiceAppRoleAssignmentFetcher alloc] initWithUrl:@"" parent:self asClass:[MSGraphServiceAppRoleAssignment class]];
}

- (MSGraphServiceGroupFetcher *)asGroup {

	return [[MSGraphServiceGroupFetcher alloc] initWithUrl:@"" parent:self asClass:[MSGraphServiceGroup class]];
}

- (MSGraphServiceContactFetcher *)asContact {

	return [[MSGraphServiceContactFetcher alloc] initWithUrl:@"" parent:self asClass:[MSGraphServiceContact class]];
}

- (MSGraphServiceDeviceFetcher *)asDevice {

	return [[MSGraphServiceDeviceFetcher alloc] initWithUrl:@"" parent:self asClass:[MSGraphServiceDevice class]];
}

- (MSGraphServiceDeviceConfigurationFetcher *)asDeviceConfiguration {

	return [[MSGraphServiceDeviceConfigurationFetcher alloc] initWithUrl:@"" parent:self asClass:[MSGraphServiceDeviceConfiguration class]];
}

- (MSGraphServiceDirectoryLinkChangeFetcher *)asDirectoryLinkChange {

	return [[MSGraphServiceDirectoryLinkChangeFetcher alloc] initWithUrl:@"" parent:self asClass:[MSGraphServiceDirectoryLinkChange class]];
}

- (MSGraphServiceDirectoryRoleFetcher *)asDirectoryRole {

	return [[MSGraphServiceDirectoryRoleFetcher alloc] initWithUrl:@"" parent:self asClass:[MSGraphServiceDirectoryRole class]];
}

- (MSGraphServiceDirectoryRoleTemplateFetcher *)asDirectoryRoleTemplate {

	return [[MSGraphServiceDirectoryRoleTemplateFetcher alloc] initWithUrl:@"" parent:self asClass:[MSGraphServiceDirectoryRoleTemplate class]];
}

- (MSGraphServiceServicePrincipalFetcher *)asServicePrincipal {

	return [[MSGraphServiceServicePrincipalFetcher alloc] initWithUrl:@"" parent:self asClass:[MSGraphServiceServicePrincipal class]];
}

- (MSGraphServiceTenantDetailFetcher *)asTenantDetail {

	return [[MSGraphServiceTenantDetailFetcher alloc] initWithUrl:@"" parent:self asClass:[MSGraphServiceTenantDetail class]];
}

@end