/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSGraphServiceDirectoryObjectCollectionFetcher;
@class MSGraphServiceApplicationCollectionFetcher;
@class MSGraphServiceContactCollectionFetcher;
@class MSGraphServiceDeviceConfigurationCollectionFetcher;
@class MSGraphServiceDeviceCollectionFetcher;
@class MSGraphServiceGroupCollectionFetcher;
@class MSGraphServiceDirectoryRoleCollectionFetcher;
@class MSGraphServiceDirectoryRoleTemplateCollectionFetcher;
@class MSGraphServiceServicePrincipalCollectionFetcher;
@class MSGraphServiceTenantDetailCollectionFetcher;
@class MSGraphServiceUserCollectionFetcher;
@class MSGraphServiceOAuth2PermissionGrantCollectionFetcher;
@class MSGraphServiceSubscribedSkuCollectionFetcher;

#import <core/core.h>
#import "MSGraphServiceModels.h"

/**
* The header for type MSGraphServiceClient.
*/

@interface MSGraphServiceClient : MSOrcBaseContainer

- (instancetype)initWithUrl:(NSString *)url  dependencyResolver:(id<MSOrcDependencyResolver>)resolver;
@property (retain, nonatomic, readonly, getter=directoryObjects) MSGraphServiceDirectoryObjectCollectionFetcher *directoryObjects;
@property (retain, nonatomic, readonly, getter=applications) MSGraphServiceApplicationCollectionFetcher *applications;
@property (retain, nonatomic, readonly, getter=contacts) MSGraphServiceContactCollectionFetcher *contacts;
@property (retain, nonatomic, readonly, getter=deviceConfiguration) MSGraphServiceDeviceConfigurationCollectionFetcher *deviceConfiguration;
@property (retain, nonatomic, readonly, getter=devices) MSGraphServiceDeviceCollectionFetcher *devices;
@property (retain, nonatomic, readonly, getter=groups) MSGraphServiceGroupCollectionFetcher *groups;
@property (retain, nonatomic, readonly, getter=directoryRoles) MSGraphServiceDirectoryRoleCollectionFetcher *directoryRoles;
@property (retain, nonatomic, readonly, getter=directoryRoleTemplates) MSGraphServiceDirectoryRoleTemplateCollectionFetcher *directoryRoleTemplates;
@property (retain, nonatomic, readonly, getter=servicePrincipals) MSGraphServiceServicePrincipalCollectionFetcher *servicePrincipals;
@property (retain, nonatomic, readonly, getter=tenantDetails) MSGraphServiceTenantDetailCollectionFetcher *tenantDetails;
@property (retain, nonatomic, readonly, getter=users) MSGraphServiceUserCollectionFetcher *users;
@property (retain, nonatomic, readonly, getter=oauth2PermissionGrants) MSGraphServiceOAuth2PermissionGrantCollectionFetcher *oauth2PermissionGrants;
@property (retain, nonatomic, readonly, getter=subscribedSkus) MSGraphServiceSubscribedSkuCollectionFetcher *subscribedSkus;
@end