/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSGraphServiceAttachmentFetcher;
@class MSGraphServiceAttachmentCollectionFetcher;
@class MSGraphServiceCalendarFetcher;
@class MSGraphServiceEventFetcher;
@class MSGraphServiceEventCollectionFetcher;
@class MSGraphServiceEventOperations;

#import <core/core.h>
#import "MSGraphServiceModels.h"

/**
* The header for type MSGraphServiceEventFetcher.
*/


@interface MSGraphServiceEventFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSGraphServiceEventOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSGraphServiceEvent *event, MSOrcError *error))callback;
- (void)update:(MSGraphServiceEvent *)event callback:(void(^)(MSGraphServiceEvent *event, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSGraphServiceEventFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSGraphServiceEventFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSGraphServiceEventFetcher *)select:(NSString *)params;
- (MSGraphServiceEventFetcher *)expand:(NSString *)value;
@property (retain, nonatomic, readonly, getter=attachments) MSGraphServiceAttachmentCollectionFetcher *attachments;

- (MSGraphServiceAttachmentFetcher *)getAttachmentsById:(NSString*)id;


@property (retain, nonatomic, readonly, getter=calendar) MSGraphServiceCalendarFetcher *calendar;
@property (retain, nonatomic, readonly, getter=instances) MSGraphServiceEventCollectionFetcher *instances;

- (MSGraphServiceEventFetcher *)getInstancesById:(NSString*)id;


@end