/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSGraphServiceAppRoleAssignmentFetcher;
@class MSGraphServiceAppRoleAssignmentCollectionFetcher;
@class MSGraphServiceDirectoryObjectFetcher;
@class MSGraphServiceDirectoryObjectCollectionFetcher;
@class MSGraphServicePhotoFetcher;
@class MSGraphServicePhotoCollectionFetcher;
@class MSGraphServiceConversationFetcher;
@class MSGraphServiceConversationCollectionFetcher;
@class MSGraphServiceConversationThreadFetcher;
@class MSGraphServiceConversationThreadCollectionFetcher;
@class MSGraphServiceCalendarFetcher;
@class MSGraphServiceEventFetcher;
@class MSGraphServiceEventCollectionFetcher;
@class MSGraphServiceItemFetcher;
@class MSGraphServiceItemCollectionFetcher;
@class MSGraphServiceGroupOperations;

#import <core/core.h>
#import "MSGraphServiceModels.h"

/**
* The header for type MSGraphServiceGroupFetcher.
*/


@interface MSGraphServiceGroupFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSGraphServiceGroupOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSGraphServiceGroup *group, MSOrcError *error))callback;
- (void)update:(MSGraphServiceGroup *)group callback:(void(^)(MSGraphServiceGroup *group, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSGraphServiceGroupFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSGraphServiceGroupFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSGraphServiceGroupFetcher *)select:(NSString *)params;
- (MSGraphServiceGroupFetcher *)expand:(NSString *)value;
@property (retain, nonatomic, readonly, getter=appRoleAssignments) MSGraphServiceAppRoleAssignmentCollectionFetcher *appRoleAssignments;

- (MSGraphServiceAppRoleAssignmentFetcher *)getAppRoleAssignmentsById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=members) MSGraphServiceDirectoryObjectCollectionFetcher *members;

- (MSGraphServiceDirectoryObjectFetcher *)getMembersById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=memberOf) MSGraphServiceDirectoryObjectCollectionFetcher *memberOf;

- (MSGraphServiceDirectoryObjectFetcher *)getMemberOfById:(NSString*)id;


@property (retain, nonatomic, readonly, getter=createdOnBehalfOf) MSGraphServiceDirectoryObjectFetcher *createdOnBehalfOf;
@property (retain, nonatomic, readonly, getter=owners) MSGraphServiceDirectoryObjectCollectionFetcher *owners;

- (MSGraphServiceDirectoryObjectFetcher *)getOwnersById:(NSString*)id;


@property (retain, nonatomic, readonly, getter=groupPhoto) MSGraphServicePhotoFetcher *groupPhoto;
@property (retain, nonatomic, readonly, getter=groupPhotos) MSGraphServicePhotoCollectionFetcher *groupPhotos;

- (MSGraphServicePhotoFetcher *)getGroupPhotosById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=conversations) MSGraphServiceConversationCollectionFetcher *conversations;

- (MSGraphServiceConversationFetcher *)getConversationsById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=threads) MSGraphServiceConversationThreadCollectionFetcher *threads;

- (MSGraphServiceConversationThreadFetcher *)getThreadsById:(NSString*)id;


@property (retain, nonatomic, readonly, getter=calendar) MSGraphServiceCalendarFetcher *calendar;
@property (retain, nonatomic, readonly, getter=events) MSGraphServiceEventCollectionFetcher *events;

- (MSGraphServiceEventFetcher *)getEventsById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=calendarView) MSGraphServiceEventCollectionFetcher *calendarView;

- (MSGraphServiceEventFetcher *)getCalendarViewById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=files) MSGraphServiceItemCollectionFetcher *files;

- (MSGraphServiceItemFetcher *)getFilesById:(NSString*)id;


@end