/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSEntityContainerServiceInfoFetcher;

#import <core/core.h>
#import "MSEntityContainerModels.h"

/**
* The header for type MSEntityContainerServiceInfoCollectionFetcher.
*/

@interface MSEntityContainerServiceInfoCollectionFetcher : MSOrcCollectionFetcher

- (instancetype)initWithUrl:(NSString *)urlComponent parent:(id<MSOrcExecutable>)parent;

- (MSEntityContainerServiceInfoFetcher *)getById:(NSString *)Id;
- (void)add:(MSEntityContainerServiceInfo *)entity callback:(void (^)(MSEntityContainerServiceInfo *serviceInfo, MSOrcError *error))callback;

- (MSEntityContainerServiceInfoCollectionFetcher *)select:(NSString *)params;
- (MSEntityContainerServiceInfoCollectionFetcher *)filter:(NSString *)params;
- (MSEntityContainerServiceInfoCollectionFetcher *)search:(NSString *)params;
- (MSEntityContainerServiceInfoCollectionFetcher *)top:(int)value;
- (MSEntityContainerServiceInfoCollectionFetcher *)skip:(int)value;
- (MSEntityContainerServiceInfoCollectionFetcher *)expand:(NSString *)value;
- (MSEntityContainerServiceInfoCollectionFetcher *)orderBy:(NSString *)params;
- (MSEntityContainerServiceInfoCollectionFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSEntityContainerServiceInfoCollectionFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;

@end