/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSEntityContainerEventFetcher;
@class MSEntityContainerEventCollectionFetcher;
@class MSEntityContainerCalendarOperations;

#import <core/core.h>
#import "MSEntityContainerModels.h"

/**
* The header for type MSEntityContainerCalendarFetcher.
*/


@interface MSEntityContainerCalendarFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSEntityContainerCalendarOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSEntityContainerCalendar *calendar, MSOrcError *error))callback;
- (void)update:(MSEntityContainerCalendar *)calendar callback:(void(^)(MSEntityContainerCalendar *calendar, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSEntityContainerCalendarFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSEntityContainerCalendarFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSEntityContainerCalendarFetcher *)select:(NSString *)params;
- (MSEntityContainerCalendarFetcher *)expand:(NSString *)value;
@property (retain, nonatomic, readonly, getter=calendarView) MSEntityContainerEventCollectionFetcher *calendarView;

- (MSEntityContainerEventFetcher *)getCalendarViewById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=events) MSEntityContainerEventCollectionFetcher *events;

- (MSEntityContainerEventFetcher *)getEventsById:(NSString*)id;


@end