/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSEntityContainerAttachmentFetcher;
@class MSEntityContainerAttachmentCollectionFetcher;
@class MSEntityContainerCalendarFetcher;
@class MSEntityContainerEventFetcher;
@class MSEntityContainerEventCollectionFetcher;
@class MSEntityContainerEventOperations;

#import <core/core.h>
#import "MSEntityContainerModels.h"

/**
* The header for type MSEntityContainerEventFetcher.
*/


@interface MSEntityContainerEventFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSEntityContainerEventOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSEntityContainerEvent *event, MSOrcError *error))callback;
- (void)update:(MSEntityContainerEvent *)event callback:(void(^)(MSEntityContainerEvent *event, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSEntityContainerEventFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSEntityContainerEventFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSEntityContainerEventFetcher *)select:(NSString *)params;
- (MSEntityContainerEventFetcher *)expand:(NSString *)value;
@property (retain, nonatomic, readonly, getter=attachments) MSEntityContainerAttachmentCollectionFetcher *attachments;

- (MSEntityContainerAttachmentFetcher *)getAttachmentsById:(NSString*)id;


@property (retain, nonatomic, readonly, getter=calendar) MSEntityContainerCalendarFetcher *calendar;
@property (retain, nonatomic, readonly, getter=instances) MSEntityContainerEventCollectionFetcher *instances;

- (MSEntityContainerEventFetcher *)getInstancesById:(NSString*)id;


@end