/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
#import "MSEntityContainerFetchers.h"

@implementation MSEntityContainerEventFetcher

@synthesize operations = _operations;

- (instancetype)initWithUrl:(NSString *)urlComponent parent:(id<MSOrcExecutable>)parent {

    if (self = [super initWithUrl:urlComponent parent:parent asClass:[MSEntityContainerEvent class]]) {

		_operations = [[MSEntityContainerEventOperations alloc] initOperationWithUrl:urlComponent parent:parent];
    }

    return self;
}

- (void)update:(id)entity callback:(void (^)(MSEntityContainerEvent *event, MSOrcError *e))callback {

	return [super update:entity callback:callback];
}

- (void)delete:(void (^)(int status, MSOrcError *e))callback {

	return [super deleteWithCallback:callback];
}

- (MSEntityContainerEventFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value {
    [super addCustomParametersWithName:name value:value];
    
    return self;
}

- (MSEntityContainerEventFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value {
    [super addCustomHeaderWithName:name value:value];
    
    return self;
}

- (MSEntityContainerEventFetcher *)select:(NSString *)params {
    [super select:params];
    
    return self;
}

- (MSEntityContainerEventFetcher *)expand:(NSString *)value {
    [super select:value];
    
    return self;
}

- (void) readWithCallback:(void (^)(MSEntityContainerEvent *event, MSOrcError *error))callback {
    [super readWithCallback:^(id response, MSOrcError *error) {
        callback(response, error);
    }];
}

- (MSEntityContainerAttachmentCollectionFetcher *)attachments {

    return [[MSEntityContainerAttachmentCollectionFetcher alloc] initWithUrl:@"Attachments" parent:self asClass:[MSEntityContainerAttachment class]];
}

- (MSEntityContainerAttachmentFetcher *)getAttachmentsById:(NSString *)id {

    return [[[MSEntityContainerAttachmentCollectionFetcher alloc] initWithUrl:@"Attachments" parent:self asClass:[MSEntityContainerAttachment class]] getById:id];
}

- (MSEntityContainerCalendarFetcher *)calendar {

	 return [[MSEntityContainerCalendarFetcher alloc] initWithUrl:@"Calendar" parent:self asClass:[MSEntityContainerCalendar class]];
}

- (MSEntityContainerEventCollectionFetcher *)instances {

    return [[MSEntityContainerEventCollectionFetcher alloc] initWithUrl:@"Instances" parent:self asClass:[MSEntityContainerEvent class]];
}

- (MSEntityContainerEventFetcher *)getInstancesById:(NSString *)id {

    return [[[MSEntityContainerEventCollectionFetcher alloc] initWithUrl:@"Instances" parent:self asClass:[MSEntityContainerEvent class]] getById:id];
}

@end