/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSEntityContainerItemAttachmentFetcher;

#import <core/core.h>
#import "MSEntityContainerModels.h"

/**
* The header for type MSEntityContainerItemAttachmentCollectionFetcher.
*/

@interface MSEntityContainerItemAttachmentCollectionFetcher : MSOrcCollectionFetcher

- (instancetype)initWithUrl:(NSString *)urlComponent parent:(id<MSOrcExecutable>)parent;

- (MSEntityContainerItemAttachmentFetcher *)getById:(NSString *)Id;
- (void)add:(MSEntityContainerItemAttachment *)entity callback:(void (^)(MSEntityContainerItemAttachment *itemAttachment, MSOrcError *error))callback;

- (MSEntityContainerItemAttachmentCollectionFetcher *)select:(NSString *)params;
- (MSEntityContainerItemAttachmentCollectionFetcher *)filter:(NSString *)params;
- (MSEntityContainerItemAttachmentCollectionFetcher *)search:(NSString *)params;
- (MSEntityContainerItemAttachmentCollectionFetcher *)top:(int)value;
- (MSEntityContainerItemAttachmentCollectionFetcher *)skip:(int)value;
- (MSEntityContainerItemAttachmentCollectionFetcher *)expand:(NSString *)value;
- (MSEntityContainerItemAttachmentCollectionFetcher *)orderBy:(NSString *)params;
- (MSEntityContainerItemAttachmentCollectionFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSEntityContainerItemAttachmentCollectionFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;

@end