/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
#import "MSEntityContainerFetchers.h"

@implementation MSEntityContainerEntityFetcher

@synthesize operations = _operations;

- (instancetype)initWithUrl:(NSString *)urlComponent parent:(id<MSOrcExecutable>)parent {

    if (self = [super initWithUrl:urlComponent parent:parent asClass:[MSEntityContainerEntity class]]) {

		_operations = [[MSEntityContainerEntityOperations alloc] initOperationWithUrl:urlComponent parent:parent];
    }

    return self;
}

- (void)update:(id)entity callback:(void (^)(MSEntityContainerEntity *entity, MSOrcError *e))callback {

	return [super update:entity callback:callback];
}

- (void)delete:(void (^)(int status, MSOrcError *e))callback {

	return [super deleteWithCallback:callback];
}

- (MSEntityContainerEntityFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value {
    [super addCustomParametersWithName:name value:value];
    
    return self;
}

- (MSEntityContainerEntityFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value {
    [super addCustomHeaderWithName:name value:value];
    
    return self;
}

- (MSEntityContainerEntityFetcher *)select:(NSString *)params {
    [super select:params];
    
    return self;
}

- (MSEntityContainerEntityFetcher *)expand:(NSString *)value {
    [super select:value];
    
    return self;
}

- (void) readWithCallback:(void (^)(MSEntityContainerEntity *entity, MSOrcError *error))callback {
    [super readWithCallback:^(id response, MSOrcError *error) {
        callback(response, error);
    }];
}

- (MSEntityContainerAttachmentFetcher *)asAttachment {

	return [[MSEntityContainerAttachmentFetcher alloc] initWithUrl:@"" parent:self asClass:[MSEntityContainerAttachment class]];
}

- (MSEntityContainerItemFetcher *)asItem {

	return [[MSEntityContainerItemFetcher alloc] initWithUrl:@"" parent:self asClass:[MSEntityContainerItem class]];
}

- (MSEntityContainerDirectoryObjectFetcher *)asDirectoryObject {

	return [[MSEntityContainerDirectoryObjectFetcher alloc] initWithUrl:@"" parent:self asClass:[MSEntityContainerDirectoryObject class]];
}

- (MSEntityContainerFolderFetcher *)asFolder {

	return [[MSEntityContainerFolderFetcher alloc] initWithUrl:@"" parent:self asClass:[MSEntityContainerFolder class]];
}

- (MSEntityContainerCalendarFetcher *)asCalendar {

	return [[MSEntityContainerCalendarFetcher alloc] initWithUrl:@"" parent:self asClass:[MSEntityContainerCalendar class]];
}

- (MSEntityContainerCalendarGroupFetcher *)asCalendarGroup {

	return [[MSEntityContainerCalendarGroupFetcher alloc] initWithUrl:@"" parent:self asClass:[MSEntityContainerCalendarGroup class]];
}

- (MSEntityContainerContactFolderFetcher *)asContactFolder {

	return [[MSEntityContainerContactFolderFetcher alloc] initWithUrl:@"" parent:self asClass:[MSEntityContainerContactFolder class]];
}

@end