/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSEntityContainerMessageFetcher;
@class MSEntityContainerMessageCollectionFetcher;
@class MSEntityContainerFolderFetcher;
@class MSEntityContainerFolderCollectionFetcher;
@class MSEntityContainerFolderOperations;

#import <core/core.h>
#import "MSEntityContainerModels.h"

/**
* The header for type MSEntityContainerFolderFetcher.
*/


@interface MSEntityContainerFolderFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSEntityContainerFolderOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSEntityContainerFolder *folder, MSOrcError *error))callback;
- (void)update:(MSEntityContainerFolder *)folder callback:(void(^)(MSEntityContainerFolder *folder, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSEntityContainerFolderFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSEntityContainerFolderFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSEntityContainerFolderFetcher *)select:(NSString *)params;
- (MSEntityContainerFolderFetcher *)expand:(NSString *)value;
@property (retain, nonatomic, readonly, getter=messages) MSEntityContainerMessageCollectionFetcher *messages;

- (MSEntityContainerMessageFetcher *)getMessagesById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=childFolders) MSEntityContainerFolderCollectionFetcher *childFolders;

- (MSEntityContainerFolderFetcher *)getChildFoldersById:(NSString*)id;


@end