/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSEntityContainerMessageFetcher;
@class MSEntityContainerEventFetcher;
@class MSEntityContainerContactFetcher;
@class MSEntityContainerItemOperations;

#import <core/core.h>
#import "MSEntityContainerModels.h"

/**
* The header for type MSEntityContainerItemFetcher.
*/


@interface MSEntityContainerItemFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSEntityContainerItemOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSEntityContainerItem *item, MSOrcError *error))callback;
- (void)update:(MSEntityContainerItem *)item callback:(void(^)(MSEntityContainerItem *item, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSEntityContainerItemFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSEntityContainerItemFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSEntityContainerItemFetcher *)select:(NSString *)params;
- (MSEntityContainerItemFetcher *)expand:(NSString *)value;
- (MSEntityContainerMessageFetcher *)asMessage;	
- (MSEntityContainerEventFetcher *)asEvent;	
- (MSEntityContainerContactFetcher *)asContact;	

@end