/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
#import "MSEntityContainerFetchers.h"

@implementation MSEntityContainerItemFetcher

@synthesize operations = _operations;

- (instancetype)initWithUrl:(NSString *)urlComponent parent:(id<MSOrcExecutable>)parent {

    if (self = [super initWithUrl:urlComponent parent:parent asClass:[MSEntityContainerItem class]]) {

		_operations = [[MSEntityContainerItemOperations alloc] initOperationWithUrl:urlComponent parent:parent];
    }

    return self;
}

- (void)update:(id)entity callback:(void (^)(MSEntityContainerItem *item, MSOrcError *e))callback {

	return [super update:entity callback:callback];
}

- (void)delete:(void (^)(int status, MSOrcError *e))callback {

	return [super deleteWithCallback:callback];
}

- (MSEntityContainerItemFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value {
    [super addCustomParametersWithName:name value:value];
    
    return self;
}

- (MSEntityContainerItemFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value {
    [super addCustomHeaderWithName:name value:value];
    
    return self;
}

- (MSEntityContainerItemFetcher *)select:(NSString *)params {
    [super select:params];
    
    return self;
}

- (MSEntityContainerItemFetcher *)expand:(NSString *)value {
    [super select:value];
    
    return self;
}

- (void) readWithCallback:(void (^)(MSEntityContainerItem *item, MSOrcError *error))callback {
    [super readWithCallback:^(id response, MSOrcError *error) {
        callback(response, error);
    }];
}

- (MSEntityContainerMessageFetcher *)asMessage {

	return [[MSEntityContainerMessageFetcher alloc] initWithUrl:@"" parent:self asClass:[MSEntityContainerMessage class]];
}

- (MSEntityContainerEventFetcher *)asEvent {

	return [[MSEntityContainerEventFetcher alloc] initWithUrl:@"" parent:self asClass:[MSEntityContainerEvent class]];
}

- (MSEntityContainerContactFetcher *)asContact {

	return [[MSEntityContainerContactFetcher alloc] initWithUrl:@"" parent:self asClass:[MSEntityContainerContact class]];
}

@end