/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSEntityContainerAttachmentFetcher;
@class MSEntityContainerItemFetcher;
@class MSEntityContainerDirectoryObjectFetcher;
@class MSEntityContainerFolderFetcher;
@class MSEntityContainerCalendarFetcher;
@class MSEntityContainerCalendarGroupFetcher;
@class MSEntityContainerContactFolderFetcher;
@class MSEntityContainerEntityOperations;

#import <core/core.h>
#import "MSEntityContainerModels.h"

/**
* The header for type MSEntityContainerEntityFetcher.
*/


@interface MSEntityContainerEntityFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSEntityContainerEntityOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSEntityContainerEntity *entity, MSOrcError *error))callback;
- (void)update:(MSEntityContainerEntity *)entity callback:(void(^)(MSEntityContainerEntity *entity, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSEntityContainerEntityFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSEntityContainerEntityFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSEntityContainerEntityFetcher *)select:(NSString *)params;
- (MSEntityContainerEntityFetcher *)expand:(NSString *)value;
- (MSEntityContainerAttachmentFetcher *)asAttachment;	
- (MSEntityContainerItemFetcher *)asItem;	
- (MSEntityContainerDirectoryObjectFetcher *)asDirectoryObject;	
- (MSEntityContainerFolderFetcher *)asFolder;	
- (MSEntityContainerCalendarFetcher *)asCalendar;	
- (MSEntityContainerCalendarGroupFetcher *)asCalendarGroup;	
- (MSEntityContainerContactFolderFetcher *)asContactFolder;	

@end