/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSEntityContainerAttachmentFetcher;
@class MSEntityContainerAttachmentCollectionFetcher;
@class MSEntityContainerEventMessageFetcher;
@class MSEntityContainerMessageOperations;

#import <core/core.h>
#import "MSEntityContainerModels.h"

/**
* The header for type MSEntityContainerMessageFetcher.
*/


@interface MSEntityContainerMessageFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSEntityContainerMessageOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSEntityContainerMessage *message, MSOrcError *error))callback;
- (void)update:(MSEntityContainerMessage *)message callback:(void(^)(MSEntityContainerMessage *message, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSEntityContainerMessageFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSEntityContainerMessageFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSEntityContainerMessageFetcher *)select:(NSString *)params;
- (MSEntityContainerMessageFetcher *)expand:(NSString *)value;
@property (retain, nonatomic, readonly, getter=attachments) MSEntityContainerAttachmentCollectionFetcher *attachments;

- (MSEntityContainerAttachmentFetcher *)getAttachmentsById:(NSString*)id;

- (MSEntityContainerEventMessageFetcher *)asEventMessage;	

@end