/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSEntityContainerFolderFetcher;
@class MSEntityContainerCalendarFetcher;
@class MSEntityContainerCalendarCollectionFetcher;
@class MSEntityContainerCalendarGroupFetcher;
@class MSEntityContainerCalendarGroupCollectionFetcher;
@class MSEntityContainerEventFetcher;
@class MSEntityContainerEventCollectionFetcher;
@class MSEntityContainerFolderCollectionFetcher;
@class MSEntityContainerMessageFetcher;
@class MSEntityContainerMessageCollectionFetcher;
@class MSEntityContainerContactFetcher;
@class MSEntityContainerContactCollectionFetcher;
@class MSEntityContainerContactFolderFetcher;
@class MSEntityContainerContactFolderCollectionFetcher;
@class MSEntityContainerUserOperations;

#import <core/core.h>
#import "MSEntityContainerModels.h"

/**
* The header for type MSEntityContainerUserFetcher.
*/


@interface MSEntityContainerUserFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSEntityContainerUserOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSEntityContainerUser *user, MSOrcError *error))callback;
- (void)update:(MSEntityContainerUser *)user callback:(void(^)(MSEntityContainerUser *user, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSEntityContainerUserFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSEntityContainerUserFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSEntityContainerUserFetcher *)select:(NSString *)params;
- (MSEntityContainerUserFetcher *)expand:(NSString *)value;

@property (retain, nonatomic, readonly, getter=rootFolder) MSEntityContainerFolderFetcher *rootFolder;
@property (retain, nonatomic, readonly, getter=calendars) MSEntityContainerCalendarCollectionFetcher *calendars;

- (MSEntityContainerCalendarFetcher *)getCalendarsById:(NSString*)id;


@property (retain, nonatomic, readonly, getter=calendar) MSEntityContainerCalendarFetcher *calendar;
@property (retain, nonatomic, readonly, getter=calendarGroups) MSEntityContainerCalendarGroupCollectionFetcher *calendarGroups;

- (MSEntityContainerCalendarGroupFetcher *)getCalendarGroupsById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=events) MSEntityContainerEventCollectionFetcher *events;

- (MSEntityContainerEventFetcher *)getEventsById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=calendarView) MSEntityContainerEventCollectionFetcher *calendarView;

- (MSEntityContainerEventFetcher *)getCalendarViewById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=folders) MSEntityContainerFolderCollectionFetcher *folders;

- (MSEntityContainerFolderFetcher *)getFoldersById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=messages) MSEntityContainerMessageCollectionFetcher *messages;

- (MSEntityContainerMessageFetcher *)getMessagesById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=contacts) MSEntityContainerContactCollectionFetcher *contacts;

- (MSEntityContainerContactFetcher *)getContactsById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=contactFolders) MSEntityContainerContactFolderCollectionFetcher *contactFolders;

- (MSEntityContainerContactFolderFetcher *)getContactFoldersById:(NSString*)id;


@end