/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSOneNoteApiNotebookFetcher;
@class MSOneNoteApiNotebookCollectionFetcher;
@class MSOneNoteApiSectionFetcher;
@class MSOneNoteApiSectionCollectionFetcher;
@class MSOneNoteApiSectionGroupFetcher;
@class MSOneNoteApiSectionGroupCollectionFetcher;
@class MSOneNoteApiPageFetcher;
@class MSOneNoteApiPageCollectionFetcher;
@class MSOneNoteApiResourceFetcher;
@class MSOneNoteApiResourceCollectionFetcher;
@class MSOneNoteApiNotesOperations;

#import <core/core.h>
#import "MSOneNoteApiModels.h"

/**
* The header for type MSOneNoteApiNotesFetcher.
*/


@interface MSOneNoteApiNotesFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSOneNoteApiNotesOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSOneNoteApiNotes *notes, MSOrcError *error))callback;
- (void)update:(MSOneNoteApiNotes *)notes callback:(void(^)(MSOneNoteApiNotes *notes, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSOneNoteApiNotesFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSOneNoteApiNotesFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSOneNoteApiNotesFetcher *)select:(NSString *)params;
- (MSOneNoteApiNotesFetcher *)expand:(NSString *)value;
@property (retain, nonatomic, readonly, getter=notebooks) MSOneNoteApiNotebookCollectionFetcher *notebooks;

- (MSOneNoteApiNotebookFetcher *)getNotebooksById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=sections) MSOneNoteApiSectionCollectionFetcher *sections;

- (MSOneNoteApiSectionFetcher *)getSectionsById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=sectionGroups) MSOneNoteApiSectionGroupCollectionFetcher *sectionGroups;

- (MSOneNoteApiSectionGroupFetcher *)getSectionGroupsById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=pages) MSOneNoteApiPageCollectionFetcher *pages;

- (MSOneNoteApiPageFetcher *)getPagesById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=resources) MSOneNoteApiResourceCollectionFetcher *resources;

- (MSOneNoteApiResourceFetcher *)getResourcesById:(NSString*)id;


@end