/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSOneNoteApiNotebookFetcher;
@class MSOneNoteApiSectionGroupFetcher;
@class MSOneNoteApiSectionFetcher;
@class MSOneNoteApiSectionCollectionFetcher;
@class MSOneNoteApiSectionGroupCollectionFetcher;
@class MSOneNoteApiSectionGroupOperations;

#import <core/core.h>
#import "MSOneNoteApiModels.h"

/**
* The header for type MSOneNoteApiSectionGroupFetcher.
*/


@interface MSOneNoteApiSectionGroupFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSOneNoteApiSectionGroupOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSOneNoteApiSectionGroup *sectionGroup, MSOrcError *error))callback;
- (void)update:(MSOneNoteApiSectionGroup *)sectionGroup callback:(void(^)(MSOneNoteApiSectionGroup *sectionGroup, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSOneNoteApiSectionGroupFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSOneNoteApiSectionGroupFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSOneNoteApiSectionGroupFetcher *)select:(NSString *)params;
- (MSOneNoteApiSectionGroupFetcher *)expand:(NSString *)value;

@property (retain, nonatomic, readonly, getter=parentNotebook) MSOneNoteApiNotebookFetcher *parentNotebook;

@property (retain, nonatomic, readonly, getter=parentSectionGroup) MSOneNoteApiSectionGroupFetcher *parentSectionGroup;
@property (retain, nonatomic, readonly, getter=sections) MSOneNoteApiSectionCollectionFetcher *sections;

- (MSOneNoteApiSectionFetcher *)getSectionsById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=sectionGroups) MSOneNoteApiSectionGroupCollectionFetcher *sectionGroups;

- (MSOneNoteApiSectionGroupFetcher *)getSectionGroupsById:(NSString*)id;


@end