/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSOneNoteApiSiteCollectionFetcher;
@class MSOneNoteApiSiteCollectionCollectionFetcher;
@class MSOneNoteApiGroupFetcher;
@class MSOneNoteApiGroupCollectionFetcher;
@class MSOneNoteApiMyOrganizationOperations;

#import <core/core.h>
#import "MSOneNoteApiModels.h"

/**
* The header for type MSOneNoteApiMyOrganizationFetcher.
*/


@interface MSOneNoteApiMyOrganizationFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSOneNoteApiMyOrganizationOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSOneNoteApiMyOrganization *myOrganization, MSOrcError *error))callback;
- (void)update:(MSOneNoteApiMyOrganization *)myOrganization callback:(void(^)(MSOneNoteApiMyOrganization *myOrganization, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSOneNoteApiMyOrganizationFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSOneNoteApiMyOrganizationFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSOneNoteApiMyOrganizationFetcher *)select:(NSString *)params;
- (MSOneNoteApiMyOrganizationFetcher *)expand:(NSString *)value;
@property (retain, nonatomic, readonly, getter=siteCollections) MSOneNoteApiSiteCollectionCollectionFetcher *siteCollections;

- (MSOneNoteApiSiteCollectionFetcher *)getSiteCollectionsById:(NSString*)id;

@property (retain, nonatomic, readonly, getter=groups) MSOneNoteApiGroupCollectionFetcher *groups;

- (MSOneNoteApiGroupFetcher *)getGroupsById:(NSString*)id;


@end