/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
#import "MSOneNoteApiMeCollectionFetcher.h"
#import "MSOneNoteApiMeCollectionOperations.h"
#import "MSOneNoteApiMeFetcher.h"
#import "MSOneNoteApiMeOperations.h"
#import "MSOneNoteApiMyOrganizationCollectionFetcher.h"
#import "MSOneNoteApiMyOrganizationCollectionOperations.h"
#import "MSOneNoteApiMyOrganizationFetcher.h"
#import "MSOneNoteApiMyOrganizationOperations.h"
#import "MSOneNoteApiNotesCollectionFetcher.h"
#import "MSOneNoteApiNotesCollectionOperations.h"
#import "MSOneNoteApiNotesFetcher.h"
#import "MSOneNoteApiNotesOperations.h"
#import "MSOneNoteApiNotebookCollectionFetcher.h"
#import "MSOneNoteApiNotebookCollectionOperations.h"
#import "MSOneNoteApiNotebookFetcher.h"
#import "MSOneNoteApiNotebookOperations.h"
#import "MSOneNoteApiSectionGroupCollectionFetcher.h"
#import "MSOneNoteApiSectionGroupCollectionOperations.h"
#import "MSOneNoteApiSectionGroupFetcher.h"
#import "MSOneNoteApiSectionGroupOperations.h"
#import "MSOneNoteApiSectionCollectionFetcher.h"
#import "MSOneNoteApiSectionCollectionOperations.h"
#import "MSOneNoteApiSectionFetcher.h"
#import "MSOneNoteApiSectionOperations.h"
#import "MSOneNoteApiPageCollectionFetcher.h"
#import "MSOneNoteApiPageCollectionOperations.h"
#import "MSOneNoteApiPageFetcher.h"
#import "MSOneNoteApiPageOperations.h"
#import "MSOneNoteApiResourceCollectionFetcher.h"
#import "MSOneNoteApiResourceCollectionOperations.h"
#import "MSOneNoteApiResourceFetcher.h"
#import "MSOneNoteApiResourceOperations.h"
#import "MSOneNoteApiSiteCollectionCollectionFetcher.h"
#import "MSOneNoteApiSiteCollectionCollectionOperations.h"
#import "MSOneNoteApiSiteCollectionFetcher.h"
#import "MSOneNoteApiSiteCollectionOperations.h"
#import "MSOneNoteApiSiteCollectionFetcher.h"
#import "MSOneNoteApiSiteCollectionOperations.h"
#import "MSOneNoteApiSiteFetcher.h"
#import "MSOneNoteApiSiteOperations.h"
#import "MSOneNoteApiGroupCollectionFetcher.h"
#import "MSOneNoteApiGroupCollectionOperations.h"
#import "MSOneNoteApiGroupFetcher.h"
#import "MSOneNoteApiGroupOperations.h"

#import "MSOneNoteApiClient.h" 
