/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/
@class MSOneNoteApiNotebookFetcher;
@class MSOneNoteApiSectionGroupFetcher;
@class MSOneNoteApiPageFetcher;
@class MSOneNoteApiPageCollectionFetcher;
@class MSOneNoteApiSectionOperations;

#import <core/core.h>
#import "MSOneNoteApiModels.h"

/**
* The header for type MSOneNoteApiSectionFetcher.
*/


@interface MSOneNoteApiSectionFetcher : MSOrcEntityFetcher

@property (copy, nonatomic, readonly) MSOneNoteApiSectionOperations *operations;

- (instancetype)initWithUrl:(NSString*)urlComponent parent:(id<MSOrcExecutable>)parent;
- (void) readWithCallback:(void (^)(MSOneNoteApiSection *section, MSOrcError *error))callback;
- (void)update:(MSOneNoteApiSection *)section callback:(void(^)(MSOneNoteApiSection *section, MSOrcError *error))callback;
- (void)delete:(void(^)(int status, MSOrcError *error))callback;
- (MSOneNoteApiSectionFetcher *)addCustomParametersWithName:(NSString *)name value:(id)value;
- (MSOneNoteApiSectionFetcher *)addCustomHeaderWithName:(NSString *)name value:(NSString *)value;
- (MSOneNoteApiSectionFetcher *)select:(NSString *)params;
- (MSOneNoteApiSectionFetcher *)expand:(NSString *)value;

@property (retain, nonatomic, readonly, getter=parentNotebook) MSOneNoteApiNotebookFetcher *parentNotebook;

@property (retain, nonatomic, readonly, getter=parentSectionGroup) MSOneNoteApiSectionGroupFetcher *parentSectionGroup;
@property (retain, nonatomic, readonly, getter=pages) MSOneNoteApiPageCollectionFetcher *pages;

- (MSOneNoteApiPageFetcher *)getPagesById:(NSString*)id;


@end