
source 'https://github.com/Cocoapods/Specs.git'

# target :default
platform :ios, '7.0'
workspace 'all_services'

xcodeproj 'discovery/discovery'
target :discovery do
xcodeproj 'discovery/discovery'
pod 'orc', '=0.11.0'
end
target :files do
xcodeproj 'files/files'
pod 'orc', '=0.11.0'
end
target :graph do
xcodeproj 'graph/graph'
pod 'orc', '=0.11.0'
end
target :onenote do
xcodeproj 'onenote/onenote'
pod 'orc', '=0.11.0'
end
target :outlook do
xcodeproj 'outlook/outlook'
pod 'orc', '=0.11.0'
end
