/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/

#import "MSGraphServiceModels.h"

/**
* The implementation file for type MSGraphServiceConversationThread.
*/

@implementation MSGraphServiceConversationThread	

@synthesize odataType = _odataType;
@synthesize Id = _id;
@synthesize ToRecipients = _toRecipients;
@synthesize CcRecipients = _ccRecipients;
@synthesize Preview = _preview;
@synthesize Posts = _posts;

- (instancetype)init {

	if (self = [super init]) {

		_odataType = @"#Microsoft.Graph.ConversationThread";
		_toRecipients = [[NSMutableArray alloc] initWithCollectionType:@"MSGraphServiceRecipient"];
		_ccRecipients = [[NSMutableArray alloc] initWithCollectionType:@"MSGraphServiceRecipient"];
		_posts = [[NSMutableArray alloc] initWithCollectionType:@"MSGraphServicePost"];
    }

	return self;
}

- (void)setId:(NSString *) id {
    _id = id;
	[self valueChanged:id forProperty:@"Id"];
}
    
- (void)setToRecipients:(NSMutableArray *) toRecipients {
    _toRecipients = toRecipients;
	[self valueChanged:toRecipients forProperty:@"ToRecipients"];
}
    
- (void)setCcRecipients:(NSMutableArray *) ccRecipients {
    _ccRecipients = ccRecipients;
	[self valueChanged:ccRecipients forProperty:@"CcRecipients"];
}
    
- (void)setPreview:(NSString *) preview {
    _preview = preview;
	[self valueChanged:preview forProperty:@"Preview"];
}
    
- (void)setPosts:(NSMutableArray *) posts {
    _posts = posts;
	[self valueChanged:posts forProperty:@"Posts"];
}
    
@end