/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/

@class MSGraphServiceItemBody;
@class MSGraphServiceRecipient;
@class MSGraphServiceAttachment;

#import <Foundation/Foundation.h>
#import "MSGraphServiceImportance.h"
#import "MSGraphServiceOutlookItem.h"

/**
* The header for type Message.
*/

@interface MSGraphServiceMessage : MSGraphServiceOutlookItem

@property (copy, nonatomic, readwrite, getter=subject, setter=setSubject:) NSString *Subject;
@property (copy, nonatomic, readwrite, getter=body, setter=setBody:) MSGraphServiceItemBody *Body;
@property (copy, nonatomic, readwrite, getter=bodyPreview, setter=setBodyPreview:) NSString *BodyPreview;
@property  (nonatomic, getter=importance, setter=setImportance:) MSGraphServiceImportance Importance;
- (void)setImportanceString:(NSString *)value;
@property (nonatomic, getter=hasAttachments, setter=setHasAttachments:) BOOL HasAttachments;
@property (copy, nonatomic, readwrite, getter=parentFolderId, setter=setParentFolderId:) NSString *ParentFolderId;
@property (copy, nonatomic, readwrite, getter=from, setter=setFrom:) MSGraphServiceRecipient *From;
@property (copy, nonatomic, readwrite, getter=sender, setter=setSender:) MSGraphServiceRecipient *Sender;
@property (copy, nonatomic, readwrite, getter=toRecipients, setter=setToRecipients:) NSMutableArray *ToRecipients;
@property (copy, nonatomic, readwrite, getter=ccRecipients, setter=setCcRecipients:) NSMutableArray *CcRecipients;
@property (copy, nonatomic, readwrite, getter=bccRecipients, setter=setBccRecipients:) NSMutableArray *BccRecipients;
@property (copy, nonatomic, readwrite, getter=replyTo, setter=setReplyTo:) NSMutableArray *ReplyTo;
@property (copy, nonatomic, readwrite, getter=conversationId, setter=setConversationId:) NSString *ConversationId;
@property (copy, nonatomic, readwrite, getter=uniqueBody, setter=setUniqueBody:) MSGraphServiceItemBody *UniqueBody;
@property (copy, nonatomic, readwrite, getter=dateTimeReceived, setter=setDateTimeReceived:) NSDate *DateTimeReceived;
@property (copy, nonatomic, readwrite, getter=dateTimeSent, setter=setDateTimeSent:) NSDate *DateTimeSent;
@property (nonatomic, getter=isDeliveryReceiptRequested, setter=setIsDeliveryReceiptRequested:) BOOL IsDeliveryReceiptRequested;
@property (nonatomic, getter=isReadReceiptRequested, setter=setIsReadReceiptRequested:) BOOL IsReadReceiptRequested;
@property (nonatomic, getter=isDraft, setter=setIsDraft:) BOOL IsDraft;
@property (nonatomic, getter=isRead, setter=setIsRead:) BOOL IsRead;
@property (copy, nonatomic, readwrite, getter=webLink, setter=setWebLink:) NSString *WebLink;
@property (copy, nonatomic, readwrite, getter=attachments, setter=setAttachments:) NSMutableArray *Attachments;

@end