/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/

@class MSGraphServiceAssignedLicense;
@class MSGraphServiceAssignedPlan;
@class MSGraphServicePasswordProfile;
@class MSGraphServiceProvisionedPlan;
@class MSGraphServiceProvisioningError;
@class NSStream;
@class MSGraphServiceAppRoleAssignment;
@class MSGraphServiceOAuth2PermissionGrant;
@class MSGraphServiceDirectoryObject;
@class MSGraphServiceMessage;
@class MSGraphServiceCalendar;
@class MSGraphServiceCalendarGroup;
@class MSGraphServiceEvent;
@class MSGraphServicePhoto;
@class MSGraphServiceFile;
@class MSGraphServiceUser;
@class MSGraphServiceGroup;
@class MSGraphServiceDrive;
@class MSGraphServiceItem;

#import <Foundation/Foundation.h>
#import "MSGraphServiceDirectoryObject.h"

/**
* The header for type User.
*/

@interface MSGraphServiceUser : MSGraphServiceDirectoryObject

@property (nonatomic, getter=accountEnabled, setter=setAccountEnabled:) BOOL accountEnabled;
@property (copy, nonatomic, readwrite, getter=assignedLicenses, setter=setAssignedLicenses:) NSMutableArray *assignedLicenses;
@property (copy, nonatomic, readwrite, getter=assignedPlans, setter=setAssignedPlans:) NSMutableArray *assignedPlans;
@property (copy, nonatomic, readwrite, getter=city, setter=setCity:) NSString *city;
@property (copy, nonatomic, readwrite, getter=country, setter=setCountry:) NSString *country;
@property (copy, nonatomic, readwrite, getter=department, setter=setDepartment:) NSString *department;
@property (nonatomic, getter=dirSyncEnabled, setter=setDirSyncEnabled:) BOOL dirSyncEnabled;
@property (copy, nonatomic, readwrite, getter=displayName, setter=setDisplayName:) NSString *displayName;
@property (copy, nonatomic, readwrite, getter=facsimileTelephoneNumber, setter=setFacsimileTelephoneNumber:) NSString *facsimileTelephoneNumber;
@property (copy, nonatomic, readwrite, getter=givenName, setter=setGivenName:) NSString *givenName;
@property (copy, nonatomic, readwrite, getter=immutableId, setter=setImmutableId:) NSString *immutableId;
@property (copy, nonatomic, readwrite, getter=jobTitle, setter=setJobTitle:) NSString *jobTitle;
@property (copy, nonatomic, readwrite, getter=lastDirSyncTime, setter=setLastDirSyncTime:) NSDate *lastDirSyncTime;
@property (copy, nonatomic, readwrite, getter=mail, setter=setMail:) NSString *mail;
@property (copy, nonatomic, readwrite, getter=mailNickname, setter=setMailNickname:) NSString *mailNickname;
@property (copy, nonatomic, readwrite, getter=mobile, setter=setMobile:) NSString *mobile;
@property (copy, nonatomic, readwrite, getter=onPremisesSecurityIdentifier, setter=setOnPremisesSecurityIdentifier:) NSString *onPremisesSecurityIdentifier;
@property (copy, nonatomic, readwrite, getter=otherMails, setter=setOtherMails:) NSMutableArray *otherMails;
@property (copy, nonatomic, readwrite, getter=passwordPolicies, setter=setPasswordPolicies:) NSString *passwordPolicies;
@property (copy, nonatomic, readwrite, getter=passwordProfile, setter=setPasswordProfile:) MSGraphServicePasswordProfile *passwordProfile;
@property (copy, nonatomic, readwrite, getter=physicalDeliveryOfficeName, setter=setPhysicalDeliveryOfficeName:) NSString *physicalDeliveryOfficeName;
@property (copy, nonatomic, readwrite, getter=postalCode, setter=setPostalCode:) NSString *postalCode;
@property (copy, nonatomic, readwrite, getter=preferredLanguage, setter=setPreferredLanguage:) NSString *preferredLanguage;
@property (copy, nonatomic, readwrite, getter=provisionedPlans, setter=setProvisionedPlans:) NSMutableArray *provisionedPlans;
@property (copy, nonatomic, readwrite, getter=provisioningErrors, setter=setProvisioningErrors:) NSMutableArray *provisioningErrors;
@property (copy, nonatomic, readwrite, getter=proxyAddresses, setter=setProxyAddresses:) NSMutableArray *proxyAddresses;
@property (copy, nonatomic, readwrite, getter=sipProxyAddress, setter=setSipProxyAddress:) NSString *sipProxyAddress;
@property (copy, nonatomic, readwrite, getter=state, setter=setState:) NSString *state;
@property (copy, nonatomic, readwrite, getter=streetAddress, setter=setStreetAddress:) NSString *streetAddress;
@property (copy, nonatomic, readwrite, getter=surname, setter=setSurname:) NSString *surname;
@property (copy, nonatomic, readwrite, getter=telephoneNumber, setter=setTelephoneNumber:) NSString *telephoneNumber;
@property (copy, nonatomic, readwrite, getter=thumbnailPhoto, setter=setThumbnailPhoto:) NSStream *thumbnailPhoto;
@property (copy, nonatomic, readwrite, getter=usageLocation, setter=setUsageLocation:) NSString *usageLocation;
@property (copy, nonatomic, readwrite, getter=userPrincipalName, setter=setUserPrincipalName:) NSString *userPrincipalName;
@property (copy, nonatomic, readwrite, getter=userType, setter=setUserType:) NSString *userType;
@property (copy, nonatomic, readwrite, getter=mailboxGuid, setter=setMailboxGuid:) NSString *MailboxGuid;
@property (copy, nonatomic, readwrite, getter=aboutMe, setter=setAboutMe:) NSString *AboutMe;
@property (copy, nonatomic, readwrite, getter=alias, setter=setAlias:) NSString *Alias;
@property (copy, nonatomic, readwrite, getter=birthday, setter=setBirthday:) NSDate *Birthday;
@property (copy, nonatomic, readwrite, getter=hireDate, setter=setHireDate:) NSDate *HireDate;
@property (copy, nonatomic, readwrite, getter=interests, setter=setInterests:) NSMutableArray *Interests;
@property (copy, nonatomic, readwrite, getter=mySite, setter=setMySite:) NSString *MySite;
@property (copy, nonatomic, readwrite, getter=pastProjects, setter=setPastProjects:) NSMutableArray *PastProjects;
@property (copy, nonatomic, readwrite, getter=preferredName, setter=setPreferredName:) NSString *PreferredName;
@property (copy, nonatomic, readwrite, getter=principalName, setter=setPrincipalName:) NSString *PrincipalName;
@property (copy, nonatomic, readwrite, getter=responsibilities, setter=setResponsibilities:) NSMutableArray *Responsibilities;
@property (copy, nonatomic, readwrite, getter=schools, setter=setSchools:) NSMutableArray *Schools;
@property (copy, nonatomic, readwrite, getter=skills, setter=setSkills:) NSMutableArray *Skills;
@property (copy, nonatomic, readwrite, getter=tags, setter=setTags:) NSMutableArray *Tags;
@property (copy, nonatomic, readwrite, getter=appRoleAssignments, setter=setAppRoleAssignments:) NSMutableArray *appRoleAssignments;
@property (copy, nonatomic, readwrite, getter=oauth2PermissionGrants, setter=setOauth2PermissionGrants:) NSMutableArray *oauth2PermissionGrants;
@property (copy, nonatomic, readwrite, getter=ownedDevices, setter=setOwnedDevices:) NSMutableArray *ownedDevices;
@property (copy, nonatomic, readwrite, getter=registeredDevices, setter=setRegisteredDevices:) NSMutableArray *registeredDevices;
@property (copy, nonatomic, readwrite, getter=manager, setter=setManager:) MSGraphServiceDirectoryObject *manager;
@property (copy, nonatomic, readwrite, getter=directReports, setter=setDirectReports:) NSMutableArray *directReports;
@property (copy, nonatomic, readwrite, getter=memberOf, setter=setMemberOf:) NSMutableArray *memberOf;
@property (copy, nonatomic, readwrite, getter=createdObjects, setter=setCreatedObjects:) NSMutableArray *createdObjects;
@property (copy, nonatomic, readwrite, getter=ownedObjects, setter=setOwnedObjects:) NSMutableArray *ownedObjects;
@property (copy, nonatomic, readwrite, getter=messages, setter=setMessages:) NSMutableArray *Messages;
@property (copy, nonatomic, readwrite, getter=calendars, setter=setCalendars:) NSMutableArray *Calendars;
@property (copy, nonatomic, readwrite, getter=calendar, setter=setCalendar:) MSGraphServiceCalendar *Calendar;
@property (copy, nonatomic, readwrite, getter=calendarGroups, setter=setCalendarGroups:) NSMutableArray *CalendarGroups;
@property (copy, nonatomic, readwrite, getter=events, setter=setEvents:) NSMutableArray *Events;
@property (copy, nonatomic, readwrite, getter=calendarView, setter=setCalendarView:) NSMutableArray *CalendarView;
@property (copy, nonatomic, readwrite, getter=userPhoto, setter=setUserPhoto:) MSGraphServicePhoto *UserPhoto;
@property (copy, nonatomic, readwrite, getter=userPhotos, setter=setUserPhotos:) NSMutableArray *UserPhotos;
@property (copy, nonatomic, readwrite, getter=trendingAround, setter=setTrendingAround:) NSMutableArray *TrendingAround;
@property (copy, nonatomic, readwrite, getter=workingWith, setter=setWorkingWith:) NSMutableArray *WorkingWith;
@property (copy, nonatomic, readwrite, getter=joinedGroups, setter=setJoinedGroups:) NSMutableArray *JoinedGroups;
@property (copy, nonatomic, readwrite, getter=drive, setter=setDrive:) MSGraphServiceDrive *drive;
@property (copy, nonatomic, readwrite, getter=files, setter=setFiles:) NSMutableArray *files;

@end