/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/

@class MSGraphServiceItemBody;
@class MSGraphServiceLocation;
@class MSGraphServiceResponseStatus;
@class MSGraphServiceAttendee;
@class MSGraphServicePatternedRecurrence;
@class MSGraphServiceRecipient;
@class MSGraphServiceAttachment;
@class MSGraphServiceCalendar;
@class MSGraphServiceEvent;

#import <Foundation/Foundation.h>
#import "MSGraphServiceImportance.h"
#import "MSGraphServiceFreeBusyStatus.h"
#import "MSGraphServiceEventType.h"
#import "MSGraphServiceOutlookItem.h"

/**
* The header for type Event.
*/

@interface MSGraphServiceEvent : MSGraphServiceOutlookItem

@property (copy, nonatomic, readwrite, getter=subject, setter=setSubject:) NSString *Subject;
@property (copy, nonatomic, readwrite, getter=body, setter=setBody:) MSGraphServiceItemBody *Body;
@property (copy, nonatomic, readwrite, getter=bodyPreview, setter=setBodyPreview:) NSString *BodyPreview;
@property  (nonatomic, getter=importance, setter=setImportance:) MSGraphServiceImportance Importance;
- (void)setImportanceString:(NSString *)value;
@property (nonatomic, getter=hasAttachments, setter=setHasAttachments:) BOOL HasAttachments;
@property (copy, nonatomic, readwrite, getter=start, setter=setStart:) NSDate *Start;
@property (copy, nonatomic, readwrite, getter=startTimeZone, setter=setStartTimeZone:) NSString *StartTimeZone;
@property (copy, nonatomic, readwrite, getter=end, setter=setEnd:) NSDate *End;
@property (copy, nonatomic, readwrite, getter=endTimeZone, setter=setEndTimeZone:) NSString *EndTimeZone;
@property (nonatomic, getter=reminder, setter=setReminder:) int Reminder;
@property (copy, nonatomic, readwrite, getter=location, setter=setLocation:) MSGraphServiceLocation *Location;
@property  (nonatomic, getter=showAs, setter=setShowAs:) MSGraphServiceFreeBusyStatus ShowAs;
- (void)setShowAsString:(NSString *)value;
@property (copy, nonatomic, readwrite, getter=responseStatus, setter=setResponseStatus:) MSGraphServiceResponseStatus *ResponseStatus;
@property (nonatomic, getter=isAllDay, setter=setIsAllDay:) BOOL IsAllDay;
@property (nonatomic, getter=isCancelled, setter=setIsCancelled:) BOOL IsCancelled;
@property (nonatomic, getter=isOrganizer, setter=setIsOrganizer:) BOOL IsOrganizer;
@property (nonatomic, getter=responseRequested, setter=setResponseRequested:) BOOL ResponseRequested;
@property  (nonatomic, getter=type, setter=setType:) MSGraphServiceEventType Type;
- (void)setTypeString:(NSString *)value;
@property (copy, nonatomic, readwrite, getter=seriesMasterId, setter=setSeriesMasterId:) NSString *SeriesMasterId;
@property (copy, nonatomic, readwrite, getter=attendees, setter=setAttendees:) NSMutableArray *Attendees;
@property (copy, nonatomic, readwrite, getter=recurrence, setter=setRecurrence:) MSGraphServicePatternedRecurrence *Recurrence;
@property (copy, nonatomic, readwrite, getter=organizer, setter=setOrganizer:) MSGraphServiceRecipient *Organizer;
@property (copy, nonatomic, readwrite, getter=iCalUId, setter=setICalUId:) NSString *iCalUId;
@property (copy, nonatomic, readwrite, getter=webLink, setter=setWebLink:) NSString *WebLink;
@property (copy, nonatomic, readwrite, getter=attachments, setter=setAttachments:) NSMutableArray *Attachments;
@property (copy, nonatomic, readwrite, getter=calendar, setter=setCalendar:) MSGraphServiceCalendar *Calendar;
@property (copy, nonatomic, readwrite, getter=instances, setter=setInstances:) NSMutableArray *Instances;

@end