/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/

#import "MSGraphServiceModels.h"

/**
* The implementation file for type MSGraphServicePost.
*/

@implementation MSGraphServicePost	

@synthesize odataType = _odataType;
@synthesize Body = _body;
@synthesize DateTimeReceived = _dateTimeReceived;
@synthesize HasAttachments = _hasAttachments;
@synthesize From = _from;
@synthesize Sender = _sender;
@synthesize ConversationThreadId = _conversationThreadId;
@synthesize ConversationId = _conversationId;
@synthesize NewParticipants = _newParticipants;
@synthesize Attachments = _attachments;
@synthesize InReplyTo = _inReplyTo;

- (instancetype)init {

	if (self = [super init]) {

		_odataType = @"#Microsoft.Graph.Post";
		_newParticipants = [[NSMutableArray alloc] initWithCollectionType:@"MSGraphServiceRecipient"];
		_attachments = [[NSMutableArray alloc] initWithCollectionType:@"MSGraphServiceAttachment"];
    }

	return self;
}

- (void)setBody:(MSGraphServiceItemBody *) body {
    _body = body;
	[self valueChanged:body forProperty:@"Body"];
}
    
- (void)setDateTimeReceived:(NSDate *) dateTimeReceived {
    _dateTimeReceived = dateTimeReceived;
	[self valueChanged:dateTimeReceived forProperty:@"DateTimeReceived"];
}
    
- (void)setHasAttachments:(BOOL ) hasAttachments {
    _hasAttachments = hasAttachments;
    [self valueChangedForBool:hasAttachments forProperty:@"HasAttachments"];
}
    
- (void)setFrom:(MSGraphServiceRecipient *) from {
    _from = from;
	[self valueChanged:from forProperty:@"From"];
}
    
- (void)setSender:(MSGraphServiceRecipient *) sender {
    _sender = sender;
	[self valueChanged:sender forProperty:@"Sender"];
}
    
- (void)setConversationThreadId:(NSString *) conversationThreadId {
    _conversationThreadId = conversationThreadId;
	[self valueChanged:conversationThreadId forProperty:@"ConversationThreadId"];
}
    
- (void)setConversationId:(NSString *) conversationId {
    _conversationId = conversationId;
	[self valueChanged:conversationId forProperty:@"ConversationId"];
}
    
- (void)setNewParticipants:(NSMutableArray *) newParticipants {
    _newParticipants = newParticipants;
	[self valueChanged:newParticipants forProperty:@"NewParticipants"];
}
    
- (void)setAttachments:(NSMutableArray *) attachments {
    _attachments = attachments;
	[self valueChanged:attachments forProperty:@"Attachments"];
}
    
- (void)setInReplyTo:(MSGraphServicePost *) inReplyTo {
    _inReplyTo = inReplyTo;
	[self valueChanged:inReplyTo forProperty:@"InReplyTo"];
}
    
@end