/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/

#import "MSGraphServiceModels.h"

/**
* The implementation file for type MSGraphServiceEventMessage.
*/

@implementation MSGraphServiceEventMessage	

@synthesize odataType = _odataType;
@synthesize MeetingMessageType = _meetingMessageType;
@synthesize Event = _event;

- (instancetype)init {

	if (self = [super init]) {

		_odataType = @"#Microsoft.Graph.EventMessage";
    }

	return self;
}
- (void)setMeetingMessageTypeString:(NSString *)value {

	if ([value isEqualToString:@"None"]) {	

		_meetingMessageType  = MSGraphService_MeetingMessageType_None;
        [self valueChangedForInt:MSGraphService_MeetingMessageType_None forProperty:@"MeetingMessageType"];
	}

	if ([value isEqualToString:@"MeetingRequest"]) {	

		_meetingMessageType  = MSGraphService_MeetingMessageType_MeetingRequest;
        [self valueChangedForInt:MSGraphService_MeetingMessageType_MeetingRequest forProperty:@"MeetingMessageType"];
	}

	if ([value isEqualToString:@"MeetingCancelled"]) {	

		_meetingMessageType  = MSGraphService_MeetingMessageType_MeetingCancelled;
        [self valueChangedForInt:MSGraphService_MeetingMessageType_MeetingCancelled forProperty:@"MeetingMessageType"];
	}

	if ([value isEqualToString:@"MeetingAccepted"]) {	

		_meetingMessageType  = MSGraphService_MeetingMessageType_MeetingAccepted;
        [self valueChangedForInt:MSGraphService_MeetingMessageType_MeetingAccepted forProperty:@"MeetingMessageType"];
	}

	if ([value isEqualToString:@"MeetingTenativelyAccepted"]) {	

		_meetingMessageType  = MSGraphService_MeetingMessageType_MeetingTenativelyAccepted;
        [self valueChangedForInt:MSGraphService_MeetingMessageType_MeetingTenativelyAccepted forProperty:@"MeetingMessageType"];
	}

	if ([value isEqualToString:@"MeetingDeclined"]) {	

		_meetingMessageType  = MSGraphService_MeetingMessageType_MeetingDeclined;
        [self valueChangedForInt:MSGraphService_MeetingMessageType_MeetingDeclined forProperty:@"MeetingMessageType"];
	}
}

- (void)setEvent:(MSGraphServiceEvent *) event {
    _event = event;
	[self valueChanged:event forProperty:@"Event"];
}
    
@end