/*******************************************************************************
**NOTE** This code was generated by a tool and will occasionally be
overwritten. We welcome comments and issues regarding this code; they will be
addressed in the generation tool. If you wish to submit pull requests, please
do so for the templates in that tool.

This code was generated by Vipr (https://github.com/microsoft/vipr) using
the T4TemplateWriter (https://github.com/msopentech/vipr-t4templatewriter).

Copyright (c) Microsoft Open Technologies, Inc. All Rights Reserved.
Licensed under the Apache License 2.0; see LICENSE in the source repository
root for authoritative license information.﻿
******************************************************************************/

#import "MSGraphServiceModels.h"

/**
* The implementation file for type MSGraphServiceConversation.
*/

@implementation MSGraphServiceConversation	

@synthesize odataType = _odataType;
@synthesize Id = _id;
@synthesize Topic = _topic;
@synthesize HasAttachments = _hasAttachments;
@synthesize LastDeliveryTime = _lastDeliveryTime;
@synthesize UniqueSenders = _uniqueSenders;
@synthesize Preview = _preview;
@synthesize Threads = _threads;

- (instancetype)init {

	if (self = [super init]) {

		_odataType = @"#Microsoft.Graph.Conversation";
		_uniqueSenders = [[NSMutableArray alloc] initWithCollectionType:@"MSGraphServiceString"];
		_threads = [[NSMutableArray alloc] initWithCollectionType:@"MSGraphServiceConversationThread"];
    }

	return self;
}

- (void)setId:(NSString *) id {
    _id = id;
	[self valueChanged:id forProperty:@"Id"];
}
    
- (void)setTopic:(NSString *) topic {
    _topic = topic;
	[self valueChanged:topic forProperty:@"Topic"];
}
    
- (void)setHasAttachments:(BOOL ) hasAttachments {
    _hasAttachments = hasAttachments;
    [self valueChangedForBool:hasAttachments forProperty:@"HasAttachments"];
}
    
- (void)setLastDeliveryTime:(NSDate *) lastDeliveryTime {
    _lastDeliveryTime = lastDeliveryTime;
	[self valueChanged:lastDeliveryTime forProperty:@"LastDeliveryTime"];
}
    
- (void)setUniqueSenders:(NSMutableArray *) uniqueSenders {
    _uniqueSenders = uniqueSenders;
	[self valueChanged:uniqueSenders forProperty:@"UniqueSenders"];
}
    
- (void)setPreview:(NSString *) preview {
    _preview = preview;
	[self valueChanged:preview forProperty:@"Preview"];
}
    
- (void)setThreads:(NSMutableArray *) threads {
    _threads = threads;
	[self valueChanged:threads forProperty:@"Threads"];
}
    
@end